#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄
#  ██
#  ██▄███▄    ▄█████▄  ██▄████▄  ██▄████▄   ▄████▄    ██▄████
#  ██▀  ▀██   ▀ ▄▄▄██  ██▀   ██  ██▀   ██  ██▄▄▄▄██   ██▀
#  ██    ██  ▄██▀▀▀██  ██    ██  ██    ██  ██▀▀▀▀▀▀   ██
#  ███▄▄██▀  ██▄▄▄███  ██    ██  ██    ██  ▀██▄▄▄▄█   ██
#  ▀▀ ▀▀▀     ▀▀▀▀ ▀▀  ▀▀    ▀▀  ▀▀    ▀▀    ▀▀▀▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Creates a colorful framed banner in the terminal.
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/helpers.sh")"
eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "f?" "frame" "Symbol to use for the banner frame" ":"
cmdarg "c?" "color" "Color of the banner (black, red, green, yellow, blue, magenta, cyan, white, gray)" "gray"

cmdarg_parse "$@"
# ---  Main script logic --- #
color="${cmdarg_cfg['color']}"
frame="${cmdarg_cfg['frame']}"

msg="${argv[*]}"

[[ -z "${msg}" ]] && log-error "Message is required"

colorCode="$(mapColor "${color}")" || log-error "Invalid color '${color}'"

# Build the banner
text="${frame}${frame}${frame}${frame} ${msg} ${frame}${frame}${frame}${frame}"
edge="${text//?/${frame}}"

# Print with color
printer "${colorCode}" "$(printf "%s\n%s\n%s\n" "${edge}" "${text}" "${edge}")"
