#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄                            ▄▄                  ▄▄▄▄
#  ██                    ██      ██                  ▀▀██
#  ██▄███▄    ▄█████▄  ███████   ██▄████▄   ▄████▄     ██      ██▄███▄
#  ██▀  ▀██   ▀ ▄▄▄██    ██      ██▀   ██  ██▄▄▄▄██    ██      ██▀  ▀██
#  ██    ██  ▄██▀▀▀██    ██      ██    ██  ██▀▀▀▀▀▀    ██      ██    ██
#  ███▄▄██▀  ██▄▄▄███    ██▄▄▄   ██    ██  ▀██▄▄▄▄█    ██▄▄▄   ███▄▄██▀
#  ▀▀ ▀▀▀     ▀▀▀▀ ▀▀     ▀▀▀▀   ▀▀    ▀▀    ▀▀▀▀▀      ▀▀▀▀   ██ ▀▀▀
#                                                              ██
#
# --- DESCRIPTION --- #
# Displays help content with bat in plain format using the 'help' language syntax
# --- DEPENDENCIES --- #
# - bat
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
bat --plain --language=help
