#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄                                      ▄▄           ██               ▄▄
#  ██                    ██                ██           ▀▀               ██
#  ██▄███▄    ▄█████▄  ███████  ██      ██ ██▄████▄   ████      ▄█████▄  ██▄████▄
#  ██▀  ▀██   ▀ ▄▄▄██    ██     ▀█  ██  █▀ ██▀   ██     ██     ██▀    ▀  ██▀   ██
#  ██    ██  ▄██▀▀▀██    ██      ██▄██▄██  ██    ██     ██     ██        ██    ██
#  ███▄▄██▀  ██▄▄▄███    ██▄▄▄   ▀██  ██▀  ██    ██  ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ██    ██
#  ▀▀ ▀▀▀     ▀▀▀▀ ▀▀     ▀▀▀▀    ▀▀  ▀▀   ▀▀    ▀▀  ▀▀▀▀▀▀▀▀    ▀▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Displays the source of a script using bat, if it exists
# --- DEPENDENCIES --- #
# - bat | batcat (bat)
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"

# ---  Main script logic --- #
script="${argv[0]}"
[[ -z "${script}" ]] && log-error "No valid input was given!"

if path="$(command -v "${script}" 2>/dev/null)"; then
  bat --style plain "${path}"
else
  log-error "Script ${script} doesn't exist!"
fi
