#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄                                      ▄▄           ██               ▄▄
#  ██                    ██                ██           ▀▀               ██
#  ██▄███▄    ▄█████▄  ███████  ██      ██ ██▄████▄   ████      ▄█████▄  ██▄████▄
#  ██▀  ▀██   ▀ ▄▄▄██    ██     ▀█  ██  █▀ ██▀   ██     ██     ██▀    ▀  ██▀   ██
#  ██    ██  ▄██▀▀▀██    ██      ██▄██▄██  ██    ██     ██     ██        ██    ██
#  ███▄▄██▀  ██▄▄▄███    ██▄▄▄   ▀██  ██▀  ██    ██  ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ██    ██
#  ▀▀ ▀▀▀     ▀▀▀▀ ▀▀     ▀▀▀▀    ▀▀  ▀▀   ▀▀    ▀▀  ▀▀▀▀▀▀▀▀    ▀▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Displays the source of a script using bat, if it exists
# --- DEPENDENCIES --- #
# - bat | batcat (bat)
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
[[ -z $1 ]] && log-error "No valid input was given!"

if path=$(command -v "$1" 2>/dev/null); then
  bat --style plain "${path}"
else
  log-error "Script $1 doesn't exist!"
fi
