#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄           ██                                                                                     ▄▄
#  ██           ▀▀                                                                   ██                ██
#  ██▄███▄    ████      ▄████▄   ████▄██▄   ▄████▄            ██      ██  ▄█████▄  ███████    ▄█████▄  ██▄████▄
#  ██▀  ▀██     ██     ██▀  ▀██  ██ ██ ██  ██▄▄▄▄██           ▀█  ██  █▀  ▀ ▄▄▄██    ██      ██▀    ▀  ██▀   ██
#  ██    ██     ██     ██    ██  ██ ██ ██  ██▀▀▀▀▀▀   █████    ██▄██▄██  ▄██▀▀▀██    ██      ██        ██    ██
#  ███▄▄██▀  ▄▄▄██▄▄▄  ▀██▄▄██▀  ██ ██ ██  ▀██▄▄▄▄█            ▀██  ██▀  ██▄▄▄███    ██▄▄▄   ▀██▄▄▄▄█  ██    ██
#  ▀▀ ▀▀▀    ▀▀▀▀▀▀▀▀    ▀▀▀▀    ▀▀ ▀▀ ▀▀    ▀▀▀▀▀              ▀▀  ▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀     ▀▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Watches and formats code changes using biome.js with configurable presets
# --- DEPENDENCIES --- #
# - biome
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "d?" "debounce" "Time to wait for new events before taking action" "5s"
cmdarg_parse "$@"

# ---  Main script logic --- #
debounce="${cmdarg_cfg['debounce']}"

watch.sh "js,mjs,cjs,ts,mts,cts,json,jsonc,jsx,tsx,vue" \
  -d "${debounce}" \
  -c "biome-check --summary ."

exit $?
