#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄           ██                                                       ▄▄                            ▄▄
#  ██           ▀▀                                                       ██                            ██
#  ██▄███▄    ████      ▄████▄   ████▄██▄   ▄████▄              ▄█████▄  ██▄████▄   ▄████▄    ▄█████▄  ██ ▄██▀
#  ██▀  ▀██     ██     ██▀  ▀██  ██ ██ ██  ██▄▄▄▄██            ██▀    ▀  ██▀   ██  ██▄▄▄▄██  ██▀    ▀  ██▄██
#  ██    ██     ██     ██    ██  ██ ██ ██  ██▀▀▀▀▀▀   █████    ██        ██    ██  ██▀▀▀▀▀▀  ██        ██▀██▄
#  ███▄▄██▀  ▄▄▄██▄▄▄  ▀██▄▄██▀  ██ ██ ██  ▀██▄▄▄▄█            ▀██▄▄▄▄█  ██    ██  ▀██▄▄▄▄█  ▀██▄▄▄▄█  ██  ▀█▄
#  ▀▀ ▀▀▀    ▀▀▀▀▀▀▀▀    ▀▀▀▀    ▀▀ ▀▀ ▀▀    ▀▀▀▀▀               ▀▀▀▀▀   ▀▀    ▀▀    ▀▀▀▀▀     ▀▀▀▀▀   ▀▀   ▀▀▀
#
#
# --- DESCRIPTION --- #
# Runs the check command and fixes changes with biome.js
# --- DEPENDENCIES --- #
# - biome
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

source cmdarg.sh

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "s" "summary" "Change the reporter type to summary"
cmdarg "u" "unsafe" "Apply unsafe fixes"

cmdarg_parse "$@"

summary=${cmdarg_cfg["summary"]}
unsafe=${cmdarg_cfg["unsafe"]}

if [[ ${summary} == true ]]; then
  cmdArray=(biome check --fix --config-path="${BIOME_CONFIG_PATH}" --reporter=summary "${cmdarg_argv[@]}")
else
  cmdArray=(biome check --fix --config-path="${BIOME_CONFIG_PATH}" "${cmdarg_argv[@]}")
fi

[[ ${unsafe} == true ]] && cmdArray+=(--unsafe)

"${cmdArray[@]}"
