#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄        ▄▄▄▄                          ▄▄                     ██
#  ██        ▀▀██                          ██                     ▀▀
#  ██▄███▄     ██       ▄█████▄  ██▄████▄  ██ ▄██▀              ████     ████▄██▄   ▄█████▄   ▄███▄██   ▄████▄
#  ██▀  ▀██    ██       ▀ ▄▄▄██  ██▀   ██  ██▄██                  ██     ██ ██ ██   ▀ ▄▄▄██  ██▀  ▀██  ██▄▄▄▄██
#  ██    ██    ██      ▄██▀▀▀██  ██    ██  ██▀██▄     █████       ██     ██ ██ ██  ▄██▀▀▀██  ██    ██  ██▀▀▀▀▀▀
#  ███▄▄██▀    ██▄▄▄   ██▄▄▄███  ██    ██  ██  ▀█▄             ▄▄▄██▄▄▄  ██ ██ ██  ██▄▄▄███  ▀██▄▄███  ▀██▄▄▄▄█
#  ▀▀ ▀▀▀       ▀▀▀▀    ▀▀▀▀ ▀▀  ▀▀    ▀▀  ▀▀   ▀▀▀            ▀▀▀▀▀▀▀▀  ▀▀ ▀▀ ▀▀   ▀▀▀▀ ▀▀   ▄▀▀▀ ██    ▀▀▀▀▀
#                                                                                             ▀████▀▀
#
# --- DESCRIPTION --- #
# Creates a blank image with given width, height and color
# --- DEPENDENCIES --- #
# - magick imagemagick
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

source cmdarg.sh

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "w?" "width" "The image's width in pixels" "1280"
cmdarg "t?" "height" "The image's height in pixels" "720"
cmdarg "c?" "color" "The image's color" "black"
cmdarg "e?" "extension" "The image's extension" "png"
cmdarg "n?" "name" "The image's name" "blank"

cmdarg_parse "$@"

width=${cmdarg_cfg['width']}
height=${cmdarg_cfg['height']}
color=${cmdarg_cfg['color']}
extension=${cmdarg_cfg['extension']}
name=${cmdarg_cfg['name']}

magick -size "${width}x${height}" \
  "xc:${color}" \
  "${name}.${extension}" &&
  log-success "Created image '${name}.${extension}' successfully"
