#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#                        ██
#   ▄█████▄   ▄█████▄  ███████   ██▄████▄   ▄█████▄  ████▄██▄   ▄████▄
#  ██▀    ▀   ▀ ▄▄▄██    ██      ██▀   ██   ▀ ▄▄▄██  ██ ██ ██  ██▄▄▄▄██
#  ██        ▄██▀▀▀██    ██      ██    ██  ▄██▀▀▀██  ██ ██ ██  ██▀▀▀▀▀▀
#  ▀██▄▄▄▄█  ██▄▄▄███    ██▄▄▄   ██    ██  ██▄▄▄███  ██ ██ ██  ▀██▄▄▄▄█
#    ▀▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀   ▀▀    ▀▀   ▀▀▀▀ ▀▀  ▀▀ ▀▀ ▀▀    ▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Spits out file names' and their content
# --- DEPENDENCIES --- #
# - bat
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
for file in "${@}"; do
  if [[ -f "${file}" ]]; then
    bat --style=header "${file}"
  else
    log-warning "file '${file}' doesn't exist"
  fi
  printf '\n'
done
