#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#                        ██
#   ▄█████▄   ▄█████▄  ███████   ██▄████▄   ▄█████▄  ████▄██▄   ▄████▄
#  ██▀    ▀   ▀ ▄▄▄██    ██      ██▀   ██   ▀ ▄▄▄██  ██ ██ ██  ██▄▄▄▄██
#  ██        ▄██▀▀▀██    ██      ██    ██  ▄██▀▀▀██  ██ ██ ██  ██▀▀▀▀▀▀
#  ▀██▄▄▄▄█  ██▄▄▄███    ██▄▄▄   ██    ██  ██▄▄▄███  ██ ██ ██  ▀██▄▄▄▄█
#    ▀▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀   ▀▀    ▀▀   ▀▀▀▀ ▀▀  ▀▀ ▀▀ ▀▀    ▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
#
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
echo -e "\n$1:"
cat "$1"
