#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                            ▄▄                        ▄▄
#            ██                            ██                        ██
#   ▄█████▄  ██▄████▄   ▄████▄    ▄█████▄  ██ ▄██▀              ▄███▄██   ▄████▄   ██▄███▄   ▄▄█████▄
#  ██▀    ▀  ██▀   ██  ██▄▄▄▄██  ██▀    ▀  ██▄██               ██▀  ▀██  ██▄▄▄▄██  ██▀  ▀██  ██▄▄▄▄ ▀
#  ██        ██    ██  ██▀▀▀▀▀▀  ██        ██▀██▄     █████    ██    ██  ██▀▀▀▀▀▀  ██    ██   ▀▀▀▀██▄
#  ▀██▄▄▄▄█  ██    ██  ▀██▄▄▄▄█  ▀██▄▄▄▄█  ██  ▀█▄             ▀██▄▄███  ▀██▄▄▄▄█  ███▄▄██▀  █▄▄▄▄▄██
#    ▀▀▀▀▀   ▀▀    ▀▀    ▀▀▀▀▀     ▀▀▀▀▀   ▀▀   ▀▀▀              ▀▀▀ ▀▀    ▀▀▀▀▀   ██ ▀▀▀     ▀▀▀▀▀▀
#                                                                                  ██
#
# --- DESCRIPTION --- #
# Checks a script's dependencies and installs them
# --- END SIGNATURE --- #

source "$(include "lib/helpers.sh")"
# ---  Main script logic --- #

# shellcheck disable=SC2120
trim() {
  local str="$(input "$@")"
  [[ -z ${str} ]] && printf '' && exit 0
  echo "${str}" | sed -e "s|^[[:space:]]*||" -e "s|[[:space:]]*$||"
}

checkDep() {
  local line exeName pkgName i
  line=$1
  pkgName=""
  i=1

  # Check for multi-packages enetries, if one is installed then skip
  while
    exeName="$(awk -F "|" "{print \$${i}}" <<<"${line}" | trim | awk '{print $1}')"
    [[ -n "${exeName}" ]]
  do
    command -v "${exeName}" &>/dev/null && return 0

    ((i++))
  done

  exeName="$(awk -F "|" '{print $1}' <<<"${line}" | trim | awk '{print $1}')"
  pkgName="$(sed -n 's/.*(\([^)]*\)).*/\1/p' <<<"${line}")"

  # Check if the line contains something inside parentheses
  if [[ -n ${pkgName} ]]; then
    echo "${pkgName}"
  else
    echo "${exeName}"
  fi

  return 0
}

installDep() {
  local pkg pkgManager installCmd
  local -a cmdArray

  pkg=$1

  pkgManager="$(get-package-manager)"
  installCmd="$(echo "${pkgManager}" | awk -F ':' '{print $NF}')"
  read -ra cmdArray <<<"${installCmd} ${pkg}"

  logInfo "Attempting to install package: ${pkg}"

  if SUDO_ASKPASS="$(get-askpass)" "${cmdArray[@]}"; then
    sleep 1 && clear
    logInfo "Installed ${pkg}"
    return 0
  else
    sleep 1 && clear
    logWarning "Couldn't install ${pkg}"
    return 1
  fi
}

checkDeps() {
  local file completed item line deps
  local -a depsArray failed

  if (("$#" != 1)); then
    logError "Invalid arguments, only a script name is accepted"
  else
    if [[ -f $1 ]]; then
      file="$1"
    else
      file="$(command -v "$1")"
    fi

    [[ ! -f ${file} ]] && logError "Script '${file}' was not found"
  fi

  deps="$(get-deps "${file}")"

  [[ "${deps}" == "x-none" ]] && return 0

  mapfile -t depsArray <<<"${deps}"

  completed=0
  for line in "${depsArray[@]}"; do
    item="$(checkDep "${line}")"
    if [[ -n "${item}" ]]; then
      installDep "${item}" || {
        completed=1
        failed+=("${item}")
      }
    fi
  done
  [[ ${completed} == 1 ]] && logError "Failed to install all dependencies ($(joinarr ', ' "${failed[@]}"))"
  return 0
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]] && (("$#" == 1)); then
  checkDeps "$1"
fi
