#!/usr/bin/env bash

fileName=$1
fileNameWithoutExtension="$(echo "${fileName}" | cut -d'.' -f1)"

clang "${fileName}" -o "${fileNameWithoutExtension}.out"

./"${fileNameWithoutExtension}.out"

rm ./"${fileNameWithoutExtension}.out"
