#!/usr/bin/env bash

set -euo pipefail

if [[ $# -eq 0 || $1 == "-"  ]]; then
  str=$(cat)
else
  str="$*"
fi

if [[ -z ${str} ]]; then
  log-error "No valid input was given"
fi

copyq copy "${str}" &>/dev/null
