#!/usr/bin/env bash

str=$1

if [[ -z ${str} || ${str} == "-" ]]; then
  read -re str
  copyq copy "${str}" &>/dev/null
elif [[ $# -gt 0 ]]; then # Check for arguments
  copyq copy "$*" &>/dev/null
else
  log-error "No valid input was given"
fi
