#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#
#                                                                ██
#   ▄█████▄   ▄████▄   ██▄███▄   ▀██  ███   ▄█████▄   ▄█████▄  ███████
#  ██▀    ▀  ██▀  ▀██  ██▀  ▀██   ██▄ ██   ██▀    ▀   ▀ ▄▄▄██    ██
#  ██        ██    ██  ██    ██    ████▀   ██        ▄██▀▀▀██    ██
#  ▀██▄▄▄▄█  ▀██▄▄██▀  ███▄▄██▀     ███    ▀██▄▄▄▄█  ██▄▄▄███    ██▄▄▄
#    ▀▀▀▀▀     ▀▀▀▀    ██ ▀▀▀       ██       ▀▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀
#                      ██         ███
#
# --- DESCRIPTION --- #
# Copies the contents of a file to the clipboard.
# --- DEPENDENCIES --- #
# - cat
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"

# ---  Main script logic --- #
file="${argv[0]}"

[[ -z "${file}" || ! -f "${file}" ]] && log-error "File ${file} not found"

clipcopy <"${file}" && log-success "Copied file ${file} contents successfully"
