#!/usr/bin/env bash

fileName="$1"

outfile=$(mktemp -t "$(basename "$0")"-XXXXXX.out)
# Delete the temp file on `EXIT` signal (i.e. when the script ends)
trap 'rm -f $outfile' EXIT

clang++ "${fileName}" -o "${outfile}" || exit

if [[ -f "${outfile}" ]]; then
  "${outfile}"
fi
