#!/usr/bin/env bash

# ---- Initialize a git repo ----- #
git init

# ---- Stage all files ----- #
eval "git add *"

# ---- Commit changes ----- #
git commit -m "init commit"

# ---- Create a new remote repo using GitHub-CLI ----- #
gh repo create

# ---- Push changes to the remote repository ----- #
git push -u origin main
