#!/usr/bin/env bash

sudo chown -R "$(whoami)" "$(command -v code)"
sudo chown -R "$(whoami)" /opt/visual-studio-code

sudo chown -R "$(whoami)" "$(command -v cursor)"
sudo chown -R "$(whoami)" /opt/cursor
sudo chown -R "$(whoami)" /usr/lib/cursor
