#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                  ▄▄     ██                         ▄▄           ██               ▄▄
#                  ██     ▀▀       ██                ██           ▀▀               ██
#   ▄████▄    ▄███▄██   ████     ███████  ██      ██ ██▄████▄   ████      ▄█████▄  ██▄████▄
#  ██▄▄▄▄██  ██▀  ▀██     ██       ██     ▀█  ██  █▀ ██▀   ██     ██     ██▀    ▀  ██▀   ██
#  ██▀▀▀▀▀▀  ██    ██     ██       ██      ██▄██▄██  ██    ██     ██     ██        ██    ██
#  ▀██▄▄▄▄█  ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄   ▀██  ██▀  ██    ██  ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ██    ██
#    ▀▀▀▀▀     ▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀    ▀▀  ▀▀   ▀▀    ▀▀  ▀▀▀▀▀▀▀▀    ▀▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Opens a command's source file in the specified or default editor
# --- DEPENDENCIES --- #
# - which
# - nano
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
file="${argv[0]}"
[[ -z "${file}" ]] && log-error "No valid input was given!"

EDITOR="${EDITOR:-nano}"

if path="$(command -v "$1" 2>/dev/null)"; then
  cd "$(dirname "${path}")" || log-error "Failed to change directory"
  "${EDITOR}" "${path}"
else
  log-error "Script ${file} doesn't exist!"
fi
