#!/usr/bin/env bash

set -euo pipefail

trap 'exit 1' SIGUSR1

[[ -z $1 ]] && log-error "No valid input was given!"

EDITOR=${EDITOR:-nano}

oldDir=$(pwd)

if path=$(which "$1" 2>/dev/null); then
  cd "$(dirname "${path}")" || log-error "Failed to change directory"
  ${EDITOR} "${path}" && cd "${oldDir}"
else
  log-error "Script $1 doesn't exist!"
fi
