#!/usr/bin/env bash
# shellcheck disable=2001
# --- SCRIPT SIGNATURE --- #
#
#                                                          ▄▄  ▄▄▄▄▄▄▄▄     ██     ▄▄▄▄            ▄▄
#                                                          ██  ▀▀▀██▀▀▀     ▀▀     ▀▀██            ██
#   ▄████▄   ▀██  ██▀  ██▄███▄    ▄█████▄  ██▄████▄   ▄███▄██     ██      ████       ██       ▄███▄██   ▄████▄
#  ██▄▄▄▄██    ████    ██▀  ▀██   ▀ ▄▄▄██  ██▀   ██  ██▀  ▀██     ██        ██       ██      ██▀  ▀██  ██▄▄▄▄██
#  ██▀▀▀▀▀▀    ▄██▄    ██    ██  ▄██▀▀▀██  ██    ██  ██    ██     ██        ██       ██      ██    ██  ██▀▀▀▀▀▀
#  ▀██▄▄▄▄█   ▄█▀▀█▄   ███▄▄██▀  ██▄▄▄███  ██    ██  ▀██▄▄███     ██     ▄▄▄██▄▄▄    ██▄▄▄   ▀██▄▄███  ▀██▄▄▄▄█
#    ▀▀▀▀▀   ▀▀▀  ▀▀▀  ██ ▀▀▀     ▀▀▀▀ ▀▀  ▀▀    ▀▀    ▀▀▀ ▀▀     ▀▀     ▀▀▀▀▀▀▀▀     ▀▀▀▀     ▀▀▀ ▀▀    ▀▀▀▀▀
#                      ██
#
# --- DESCRIPTION --- #
# Exapnds a tilde ~ to the HOME directory
# --- DEPENDENCIES --- #
# - sed
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/cmdarg.sh")"
source "$(include "lib/helpers.sh")"
source "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
sed "s|^~|${HOME}|" < <(input "$@")
