#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#     ▄▄▄▄         ▄▄                      ▄▄▄▄      ▄▄▄▄
#    ██▀▀▀         ██                      ▀▀██      ▀▀██
#  ███████    ▄███▄██             ▄█████▄    ██        ██
#    ██      ██▀  ▀██             ▀ ▄▄▄██    ██        ██
#    ██      ██    ██   █████    ▄██▀▀▀██    ██        ██
#    ██      ▀██▄▄███            ██▄▄▄███    ██▄▄▄     ██▄▄▄
#    ▀▀        ▀▀▀ ▀▀             ▀▀▀▀ ▀▀     ▀▀▀▀      ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# simple fd wrapper with nothing ignored
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

# ---  Main script logic --- #
/usr/bin/fd-find --no-ignore --hidden --no-require-git "$@"
