#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#     ▄▄▄▄                                                                                             ▄▄
#    ██▀▀▀                         ██                                                                  ██
#  ███████    ▄████▄   ██▄████▄  ███████             ▄▄█████▄   ▄████▄    ▄█████▄   ██▄████   ▄█████▄  ██▄████▄
#    ██      ██▀  ▀██  ██▀   ██    ██                ██▄▄▄▄ ▀  ██▄▄▄▄██   ▀ ▄▄▄██   ██▀      ██▀    ▀  ██▀   ██
#    ██      ██    ██  ██    ██    ██       █████     ▀▀▀▀██▄  ██▀▀▀▀▀▀  ▄██▀▀▀██   ██       ██        ██    ██
#    ██      ▀██▄▄██▀  ██    ██    ██▄▄▄             █▄▄▄▄▄██  ▀██▄▄▄▄█  ██▄▄▄███   ██       ▀██▄▄▄▄█  ██    ██
#    ▀▀        ▀▀▀▀    ▀▀    ▀▀     ▀▀▀▀              ▀▀▀▀▀▀     ▀▀▀▀▀    ▀▀▀▀ ▀▀   ▀▀         ▀▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Searches for a font in the list of installed fonts
# --- DEPENDENCIES --- #
# - rg (ripgrep)
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
fc-list |
  awk -F ':' '{print $2}' |
  rg -i "${argv[@]}" || log-error "Font '${argv[*]}' was not found"
