#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                                                              ▄▄▄▄                ▄▄▄▄         ██
#                                                              ▀▀██                ▀▀██         ▀▀
#   ▄███▄██   ▄████▄   ██▄████▄             ▄███▄██  ██▄███▄     ██                  ██       ████      ▄█████▄   ▄████▄   ██▄████▄  ▄▄█████▄   ▄████▄
#  ██▀  ▀██  ██▄▄▄▄██  ██▀   ██            ██▀  ▀██  ██▀  ▀██    ██                  ██         ██     ██▀    ▀  ██▄▄▄▄██  ██▀   ██  ██▄▄▄▄ ▀  ██▄▄▄▄██
#  ██    ██  ██▀▀▀▀▀▀  ██    ██   █████    ██    ██  ██    ██    ██       █████      ██         ██     ██        ██▀▀▀▀▀▀  ██    ██   ▀▀▀▀██▄  ██▀▀▀▀▀▀
#  ▀██▄▄███  ▀██▄▄▄▄█  ██    ██            ▀██▄▄███  ███▄▄██▀    ██▄▄▄               ██▄▄▄   ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ▀██▄▄▄▄█  ██    ██  █▄▄▄▄▄██  ▀██▄▄▄▄█
#   ▄▀▀▀ ██    ▀▀▀▀▀   ▀▀    ▀▀             ▄▀▀▀ ██  ██ ▀▀▀       ▀▀▀▀                ▀▀▀▀   ▀▀▀▀▀▀▀▀    ▀▀▀▀▀     ▀▀▀▀▀   ▀▀    ▀▀   ▀▀▀▀▀▀     ▀▀▀▀▀
#   ▀████▀▀                                 ▀████▀▀  ██
#
# --- DESCRIPTION --- #
# Generates a GPL 3.0 license LICENSE file
# --- DEPENDENCIES --- #
# - curl
# - sed
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #

curl -s https://www.gnu.org/licenses/gpl-3.0.txt >LICENSE

sed -i '1i GNU General Public License, Version 3.0\n\nCopyright (C) 2025 Ahmad Othman\n\nThis program is free software: you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see <https://www.gnu.org/licenses/>.\n\nThe full text of the GNU General Public License follows:\n' LICENSE
