#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                              ▄▄▄▄                ▄▄▄▄         ██
#                                                              ▀▀██                ▀▀██         ▀▀
#   ▄███▄██   ▄████▄   ██▄████▄             ▄███▄██  ██▄███▄     ██                  ██       ████      ▄█████▄   ▄████▄   ██▄████▄  ▄▄█████▄   ▄████▄
#  ██▀  ▀██  ██▄▄▄▄██  ██▀   ██            ██▀  ▀██  ██▀  ▀██    ██                  ██         ██     ██▀    ▀  ██▄▄▄▄██  ██▀   ██  ██▄▄▄▄ ▀  ██▄▄▄▄██
#  ██    ██  ██▀▀▀▀▀▀  ██    ██   █████    ██    ██  ██    ██    ██       █████      ██         ██     ██        ██▀▀▀▀▀▀  ██    ██   ▀▀▀▀██▄  ██▀▀▀▀▀▀
#  ▀██▄▄███  ▀██▄▄▄▄█  ██    ██            ▀██▄▄███  ███▄▄██▀    ██▄▄▄               ██▄▄▄   ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ▀██▄▄▄▄█  ██    ██  █▄▄▄▄▄██  ▀██▄▄▄▄█
#   ▄▀▀▀ ██    ▀▀▀▀▀   ▀▀    ▀▀             ▄▀▀▀ ██  ██ ▀▀▀       ▀▀▀▀                ▀▀▀▀   ▀▀▀▀▀▀▀▀    ▀▀▀▀▀     ▀▀▀▀▀   ▀▀    ▀▀   ▀▀▀▀▀▀     ▀▀▀▀▀
#   ▀████▀▀                                 ▀████▀▀  ██
#
# --- DESCRIPTION --- #
# Generates a GPL 3.0 license LICENSE file
# --- DEPENDENCIES --- #
# - wget
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #

wget -O LICENSE https://www.gnu.org/licenses/gpl-3.0.txt
