#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                             ██
#                        ██                   ▀▀
#   ▄███▄██   ▄████▄   ███████              ████     ██▄███▄
#  ██▀  ▀██  ██▄▄▄▄██    ██                   ██     ██▀  ▀██
#  ██    ██  ██▀▀▀▀▀▀    ██       █████       ██     ██    ██
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ▄▄▄██▄▄▄  ███▄▄██▀
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀             ▀▀▀▀▀▀▀▀  ██ ▀▀▀
#   ▀████▀▀                                          ██
#
# --- DESCRIPTION --- #
# Retrieves the IP address of the active network interface
# --- DEPENDENCIES --- #
# - ip
# - rg (ripgrep)
# - awk
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
IP="$(ip a | rg "$(net-interface)" | rg inet)"

if [[ -n "${IP}" ]]; then
  echo "${IP}" | awk '{print $2;exit}'
else
  log-error "No IP found"
fi
