#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                ▄▄
#                        ██                      ██
#   ▄███▄██   ▄████▄   ███████              ▄███▄██   ▄████▄   ██▄███▄   ▄▄█████▄
#  ██▀  ▀██  ██▄▄▄▄██    ██                ██▀  ▀██  ██▄▄▄▄██  ██▀  ▀██  ██▄▄▄▄ ▀
#  ██    ██  ██▀▀▀▀▀▀    ██       █████    ██    ██  ██▀▀▀▀▀▀  ██    ██   ▀▀▀▀██▄
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ▀██▄▄███  ▀██▄▄▄▄█  ███▄▄██▀  █▄▄▄▄▄██
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀               ▀▀▀ ▀▀    ▀▀▀▀▀   ██ ▀▀▀     ▀▀▀▀▀▀
#   ▀████▀▀                                                    ██
#
# --- DESCRIPTION --- #
# Extracts the script's dependencies
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

# ---  Main script logic --- #

if (($# != 1)); then
  log-error "Invalid arguments, only a script name is accepted"
else
  if [[ -f "$1" ]]; then
    file="$1"
  else
    file="$(command -v "$1")"
  fi

  [[ ! -f "${file}" ]] && log-error "Script '${file}' was not found"
fi

sed -n '/# --- DEPENDENCIES --- #/,/# --- END SIGNATURE --- #/{/\# - /p;}' "${file}" |
  replace '# - ' '' |
  grep -v " --- " || echo "x-none"
