#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                ▄▄     ██
#                        ██                      ██     ▀▀                 ██
#   ▄███▄██   ▄████▄   ███████              ▄███▄██   ████     ▄▄█████▄  ███████    ██▄████   ▄████▄
#  ██▀  ▀██  ██▄▄▄▄██    ██                ██▀  ▀██     ██     ██▄▄▄▄ ▀    ██       ██▀      ██▀  ▀██
#  ██    ██  ██▀▀▀▀▀▀    ██       █████    ██    ██     ██      ▀▀▀▀██▄    ██       ██       ██    ██
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ▀██▄▄███  ▄▄▄██▄▄▄  █▄▄▄▄▄██    ██▄▄▄    ██       ▀██▄▄██▀
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀               ▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀      ▀▀▀▀    ▀▀         ▀▀▀▀
#   ▀████▀▀
#
# --- DESCRIPTION --- #
# Prints the distro's pretty name from `/etc/os-release`.
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
source "/etc/os-release"
echo "${PRETTY_NAME}"
