#!/usr/bin/env bash

getExtensions() {
	# Get all VS Code extensions
	extensions="$(code --list-extensions)"

	# Format the extensions for the JSON file
	readarray -t array <<<"${extensions}"

	# Create the JSON content
	printf '%s\n' "${array[@]}" | jq -R . | jq -s .
}

if [[ -n $1 ]]; then
	file=$1
else
	file="extensions.json"
fi

# Check if the file already exists
if [[ -f "${file}" ]]; then
	if [[ $1 == "-o" || $2 == "-o" ]]; then
		eval getExtensions >"${file}"
		log-info "${file} has been overwritten."
	elif [[ $1 == "" || $2 == "" ]]; then
		overwrite='n'
		log-warning "${file} exists do you want to overwrite it? (y/N): "
		read -r overwrite
		if [[ ${overwrite} == "y" || ${overwrite} == "Y" ]]; then
			eval getExtensions >"${file}"
			log-info "${file} has been overwritten."
		elif [[ ${overwrite} == "n" || ${overwrite} == "N" || ${overwrite} == "" ]]; then
			log-info "Original file was not overwritten."
			exit 0
		else
			log-error "Invalid option!"
		fi
	else
		log-error "Invalid option!"
	fi
else
	touch "${file}"
	eval getExtensions >"${file}"
	log-info "${file} has been created."
fi
