#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                                                ▄▄
#                        ██                      ██
#   ▄███▄██   ▄████▄   ███████              ▄███▄██   ▄████▄   ▄▄█████▄   ▄█████▄
#  ██▀  ▀██  ██▄▄▄▄██    ██                ██▀  ▀██  ██▄▄▄▄██  ██▄▄▄▄ ▀  ██▀    ▀
#  ██    ██  ██▀▀▀▀▀▀    ██       █████    ██    ██  ██▀▀▀▀▀▀   ▀▀▀▀██▄  ██
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ▀██▄▄███  ▀██▄▄▄▄█  █▄▄▄▄▄██  ▀██▄▄▄▄█
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀               ▀▀▀ ▀▀    ▀▀▀▀▀    ▀▀▀▀▀▀     ▀▀▀▀▀
#   ▀████▀▀
#
# --- DESCRIPTION --- #
# Extracts the script's description
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #

if [[ $# -ne 1 ]]; then
  log-error "Invalid arguments, only a script name is accepted"
else
  if [[ -f $1 ]]; then
    file=$1
  else
    file=$(which $1)
  fi

  [[ ! -f ${file} ]] && log-error "Script '${file}' was not found"
fi

desc=$(
  sed -n '/# --- DESCRIPTION --- #/,/# --- DEPENDENCIES --- #/ {/\# /p;}' "${file}" |
    replace "# " ""
)

if echo "${desc}" | grep -v " --- " -q; then
  echo "${desc}" | grep -v " --- "
else
  printf ''
fi
