#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#                        ██                                      ██
#   ▄███▄██   ▄████▄   ███████              ▄████▄   ▀██  ██▀  ███████
#  ██▀  ▀██  ██▄▄▄▄██    ██                ██▄▄▄▄██    ████      ██
#  ██    ██  ██▀▀▀▀▀▀    ██       █████    ██▀▀▀▀▀▀    ▄██▄      ██
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ▀██▄▄▄▄█   ▄█▀▀█▄     ██▄▄▄
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀               ▀▀▀▀▀   ▀▀▀  ▀▀▀     ▀▀▀▀
#   ▀████▀▀
#
# --- DESCRIPTION --- #
# Exports VS Code extensions to a JSON file with options to overwrite existing files
# --- DEPENDENCIES --- #
# - code
# - jq
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"

eval "$(include "lib/helpers.sh")"

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "o" "overwrite" "Overwrite the file if it exists"

cmdarg_parse "$@"

overwrite=${cmdarg_cfg['overwrite']}
file=${cmdarg_argv[0]:-extensions.json}

getExtensions() {
  # Get all VS Code extensions
  extensions="$(code --list-extensions)"

  # Format the extensions for the JSON file
  readarray -t array <<<"${extensions}"

  # Create the JSON content
  output="$(printf '%s\n' "${array[@]}" | jq -R . | jq -s .)"
  echo "${output}"
}

# Check if the file already exists
if [[ -f "${file}" ]]; then
  if [[ ${overwrite} == true ]]; then
    getExtensions >"${file}"
    log-info "${file} has been overwritten."
  else
    if gum confirm "File: ${file} exists do you want to overwrite it?" --prompt.foreground="#DBAC66"; then
      getExtensions >"${file}"
      log-info "${file} has been overwritten."
    else
      terminate "No changes made"
    fi
  fi
else
  touch "${file}"
  getExtensions >"${file}"
  log-info "${file} has been created."
fi
