#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                                 ██
#                        ██                                       ▀▀
#   ▄███▄██   ▄████▄   ███████             ██    ██  ██▄████▄   ████      ▄███▄██  ██    ██   ▄████▄
#  ██▀  ▀██  ██▄▄▄▄██    ██                ██    ██  ██▀   ██     ██     ██▀  ▀██  ██    ██  ██▄▄▄▄██
#  ██    ██  ██▀▀▀▀▀▀    ██       █████    ██    ██  ██    ██     ██     ██    ██  ██    ██  ██▀▀▀▀▀▀
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ██▄▄▄███  ██    ██  ▄▄▄██▄▄▄  ▀██▄▄███  ██▄▄▄███  ▀██▄▄▄▄█
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀              ▀▀▀▀ ▀▀  ▀▀    ▀▀  ▀▀▀▀▀▀▀▀    ▀▀▀ ██   ▀▀▀▀ ▀▀    ▀▀▀▀▀
#   ▀████▀▀                                                                    ██
#
# --- DESCRIPTION --- #
# Filters unique lines that appear once in a file or stdin, with options for backup and array output
# --- DEPENDENCIES --- #
# - awk
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "b" "backup" "Creates a backup .bak file of the original file"
cmdarg "f" "force" "Overwrite the original file without cofirmation"
cmdarg "a" "array" "Returns the output as a bash compatible array"
cmdarg "q" "quiet" "Runs quietly without output on success"

cmdarg_parse "$@"
# ---  Main script logic --- #

useBackup="${cmdarg_cfg['backup']}"
force="${cmdarg_cfg['force']}"
useArray="${cmdarg_cfg['array']}"
quiet="${cmdarg_cfg['quiet']}"
file="${argv[0]}"

# Function to process input and remove duplicates
remove_duplicates() {
  if "${useArray}"; then
    tr ' ' '\n' |
      awk '
    {
      count[$0]++
      lines[NR] = $0
    }
    END {
      for (i = 1; i <= NR; i++) {
        if (count[lines[i]] == 1) print lines[i]
      }
    }
  ' | paste -sd " "
  else
    awk '
    {
      count[$0]++
      lines[NR] = $0
    }
    END {
      for (i = 1; i <= NR; i++) {
        if (count[lines[i]] == 1) print lines[i]
      }
    }
  '
  fi
}

if [[ -z "${file}" || "${file}" == "-" ]]; then
  # Read from stdin
  remove_duplicates
else
  tmpfile="$(mktemp)"
  trap 'rm -f $tmpfile' EXIT
  # Read from file
  if [[ -f "${file}" ]]; then
    if "${useBackup}"; then
      cp "${file}" "${file}.bak"
      "${quiet}" || log-info "Backup created as ${file}.bak"
    fi

    remove_duplicates <"${file}" >"${tmpfile}"

    # override the input file
    if "${force}"; then
      mv "${tmpfile}" "${file}"
    else
      mv -i "${tmpfile}" "${file}"
    fi

    "${quiet}" || log-info "Filtered unique lines from '${file}'!"
  else
    log-error "${file} was not found!"
  fi
fi
