#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                ▄▄
#                        ██                      ██
#   ▄███▄██   ▄████▄   ███████              ▄███▄██   ▄████▄   ▄▄█████▄   ▄█████▄
#  ██▀  ▀██  ██▄▄▄▄██    ██                ██▀  ▀██  ██▄▄▄▄██  ██▄▄▄▄ ▀  ██▀    ▀
#  ██    ██  ██▀▀▀▀▀▀    ██       █████    ██    ██  ██▀▀▀▀▀▀   ▀▀▀▀██▄  ██
#  ▀██▄▄███  ▀██▄▄▄▄█    ██▄▄▄             ▀██▄▄███  ▀██▄▄▄▄█  █▄▄▄▄▄██  ▀██▄▄▄▄█
#   ▄▀▀▀ ██    ▀▀▀▀▀      ▀▀▀▀               ▀▀▀ ▀▀    ▀▀▀▀▀    ▀▀▀▀▀▀     ▀▀▀▀▀
#   ▀████▀▀
#
# --- DESCRIPTION --- #
# Extracts a script's description
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

cmdarg_info "header" "Extracts a script's description"
cmdarg_parse "$@"
# ---  Main script logic --- #
if ((argc != 1)); then
  log-error "Invalid arguments, only a script name is accepted"
else
  if [[ -f "${argv[0]}" ]]; then
    file="${argv[0]}"
  else
    file="$(command -v "${argv[0]}")"
  fi

  [[ ! -f "${file}" ]] && log-error "Script '${file}' was not found"
fi

sed -n '
  /# --- DESCRIPTION --- #/{
    :loop
    n
    /# --- DEPENDENCIES --- #/q
    /\# /p
    b loop
  }
' "${file}" |
  sed 's|# ||g' |
  grep -v " --- " || printf ''
