#!/usr/bin/env bash

source logs.sh

getExtensions() {
	# Get all VS Code extensions
	extensions=$(code --list-extensions)

	# Format the extensions for the JSON file
	readarray -t array <<<"${extensions}"

	# Create the JSON content
	printf '%s\n' "${array[@]}" | jq -R . | jq -s .
}

file=$1 || "extensions.json"

# Check if the file already exists
if [[ -f "${file}" ]]; then
	if [[ $1 == "-o" || $2 == "-o" ]]; then
		eval getExtensions > "${file}"
		echo "${file} has been overwritten."
	elif [[ $1 == "" || $2 == "" ]]; then
		overwrite='n'
		echo "${file} exists do you want to overwrite it? (y/N): "
		read -r overwrite
		if [[ ${overwrite} == "y" || ${overwrite} == "Y" ]]; then
			eval getExtensions >"${file}"
			echo "${file} has been overwritten."
		elif [[ ${overwrite} == "n" || ${overwrite} == "N" || ${overwrite} == "" ]]; then
			echo "Original file was not overwritten."
			exit 0
		else
			log_error "Invalid option!"
		fi
	else
		log_error "Invalid option!"
	fi
else
	touch "${file}"
	eval getExtensions > "${file}"
	echo "${file} has been created."
fi
