#!/usr/bin/env bash
# --- SCRIPT SIGNATURE --- #
#
#               ██                                                                    ██
#               ▀▀       ██                                                           ▀▀       ██
#   ▄███▄██   ████     ███████              ▄█████▄   ▄████▄   ████▄██▄  ████▄██▄   ████     ███████
#  ██▀  ▀██     ██       ██                ██▀    ▀  ██▀  ▀██  ██ ██ ██  ██ ██ ██     ██       ██
#  ██    ██     ██       ██       █████    ██        ██    ██  ██ ██ ██  ██ ██ ██     ██       ██
#  ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄             ▀██▄▄▄▄█  ▀██▄▄██▀  ██ ██ ██  ██ ██ ██  ▄▄▄██▄▄▄    ██▄▄▄
#   ▄▀▀▀ ██  ▀▀▀▀▀▀▀▀     ▀▀▀▀               ▀▀▀▀▀     ▀▀▀▀    ▀▀ ▀▀ ▀▀  ▀▀ ▀▀ ▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀
#   ▀████▀▀
#
# --- DESCRIPTION --- #
# Adds a conventinal commit message or generates one with AI
# --- DEPENDENCIES --- #
# - git
# - rg (ripgrep)
# - gum
# - mdcat
# - commit-sage
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "lib/helpers.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "a" "ai" "Use AI to generate the message"
cmdarg "y" "yes" "Answer yes to all the prompts"
cmdarg "l" "local" "Commit changes without confirmation (no push)"
cmdarg "p" "push" "Commit and push without confirmation"
cmdarg "e" "edit" "Edit the message before committing"

cmdarg_parse "$@"
# ---  Main script logic --- #
useAi="${cmdarg_cfg['ai']}"
noConfirm="${cmdarg_cfg['yes']}"
local="${cmdarg_cfg['local']}"
push="${cmdarg_cfg['push']}"
edit="${cmdarg_cfg['edit']}"

is-git-repo

repoPath="$(git-root)"

choices=(
  "docs: ANY changes to documentation files (*.md, docs/*, etc.)"
  "feat: New features or significant functional changes"
  "fix: Bug fixes and error corrections"
  "style: Changes not affecting the code, e.g. formatting, semicolons, etc."
  "refactor: Code changes, neither fix a bug nor add a feature."
  "perf: Performance improvements"
  "test: Adding or updating tests"
  "build: Changes affecting the build system or external dependencies."
  "ci: CI/CD changes"
  "chore: Updates to build configuration, libraries, and other maintenance tasks."
  "revert: Reverting a previous commit."
)

declare -a files

cleanup() {
  killwait "${SPINNER_PID}"
  rm -f "${logFile}"
}

trap 'cleanup' EXIT

[[ -z "$(git status --porcelain)" ]] && terminate "Nothing to commit"

if ! git status --porcelain | rg '^[A-Z]' &>/dev/null; then
  output=$(
    git status --porcelain |
      rg -v '^[MAD]' |
      trim |
      gum choose \
        --no-limit \
        --header="Choose files to stage:" \
        --header.foreground="${U_GREEN}" \
        --select-if-one
  ) || terminate

  # Parse output to extract file names, preserving spaces
  declare -a files
  mapfile -t files < <(
    echo "${output}" |
      cut -d " " -f 2- |
      tr -d '"' |
      sed -E 's|^[?[:space:]]{3}||'
  ) || terminate

  for file in "${files[@]}"; do
    git add "${repoPath}/${file}"
  done
fi

if [[ "${useAi}" == true ]]; then
  logFile=$(mktemp -t commit-sage-XXXXX.log)

  # Another implementation
  spinner.sh &
  # Capture the PID immediately after launching
  SPINNER_PID=$!
  if ! commit-sage >"${logFile}" 2>&1; then
    killwait "${SPINNER_PID}"
    log-error "$(sed 's|\[ERROR\] ||' "${logFile}")"
  fi

  killwait "${SPINNER_PID}"

  # Check for [ERROR] lines after execution
  if rg -q '\[ERROR\].' "${logFile}"; then
    log-error "$(sed 's|\[ERROR\] ||' "${logFile}")"
  fi

  transformed=$(tr "\n" "#" <"${logFile}")

  summary=$(echo "${transformed}" | awk -F "##" '{print $1}' | sed 's|#$||g')
  details=$(echo "${transformed}" | awk -F "##" '{print $2}' | tr "#" "\n")

else
  type=$(
    gum filter \
      --placeholder "Commit type..." "${choices[@]}" |
      cut -d ':' -f 1
  ) || terminate

  if [[ "${edit}" == true ]]; then
    summary="${type}: "
    details=""
  else
    summary=$(
      gum input \
        --value "${type}: " \
        --placeholder "Summary of this change"
    )

    details=$(gum write --placeholder "Details of this change") || terminate
  fi
fi

if [[ "${edit}" == true ]]; then
  if git commit -m "${summary}" -m "${details}" -e; then
    log-success "Committed Changes Locally!"
  else
    # Commit failed (e.g., due to pre-commit hook)
    log-error "Commit failed!"
  fi
else

  echo -e "${summary}\n\n${details}\n\n" | mdcat

  if [[ "${noConfirm}" != true ]]; then
    gum confirm "Commit changes?" || terminate
  fi

  if git commit -m "${summary}" -m "${details}"; then
    log-success "Committed Changes Locally!"
  else
    # Commit failed (e.g., due to pre-commit hook)
    log-error "Commit failed!"
  fi
fi

if [[ -n "$(git remote -v)" && "${local}" != true ]]; then
  if [[ "${noConfirm}" != true ]]; then
    gum confirm "Push changes?" || terminate
  fi

  branch="$(git_current_branch)"
  if git push origin "${branch}"; then
    log-success "Changes pushed to ${branch} successfully!"
  else
    log-error "Failed to push to ${branch}."
  fi
fi

exit 0
