#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#               ██                                                                                                         ▄▄                                                ▄▄
#               ▀▀       ██                                                                              ██                ██                                                ██
#   ▄███▄██   ████     ███████              ▄█████▄  ██    ██   ██▄████   ██▄████   ▄████▄   ██▄████▄  ███████             ██▄███▄    ██▄████   ▄█████▄  ██▄████▄   ▄█████▄  ██▄████▄
#  ██▀  ▀██     ██       ██                ██▀    ▀  ██    ██   ██▀       ██▀      ██▄▄▄▄██  ██▀   ██    ██                ██▀  ▀██   ██▀       ▀ ▄▄▄██  ██▀   ██  ██▀    ▀  ██▀   ██
#  ██    ██     ██       ██                ██        ██    ██   ██        ██       ██▀▀▀▀▀▀  ██    ██    ██                ██    ██   ██       ▄██▀▀▀██  ██    ██  ██        ██    ██
#  ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄             ▀██▄▄▄▄█  ██▄▄▄███   ██        ██       ▀██▄▄▄▄█  ██    ██    ██▄▄▄             ███▄▄██▀   ██       ██▄▄▄███  ██    ██  ▀██▄▄▄▄█  ██    ██
#   ▄▀▀▀ ██  ▀▀▀▀▀▀▀▀     ▀▀▀▀               ▀▀▀▀▀    ▀▀▀▀ ▀▀   ▀▀        ▀▀         ▀▀▀▀▀   ▀▀    ▀▀     ▀▀▀▀             ▀▀ ▀▀▀     ▀▀        ▀▀▀▀ ▀▀  ▀▀    ▀▀    ▀▀▀▀▀   ▀▀    ▀▀
#   ▀████▀▀
#                               ▀▀▀▀▀▀▀▀▀▀                                                                      ▀▀▀▀▀▀▀▀▀▀
# --- DESCRIPTION --- #
# Displays the name of the current Git branch
# --- DEPENDENCIES --- #
# - git
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
is-git-repo

git branch --show-current 2>/dev/null
