#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#               ██                  ██                                                                                        ▄▄▄▄                                 ▄▄
#               ▀▀       ██         ▀▀                                                                                       ██▀▀▀                                 ██
#   ▄███▄██   ████     ███████    ████      ▄███▄██  ██▄████▄   ▄████▄    ██▄████   ▄████▄              ██▄████   ▄████▄   ███████    ██▄████   ▄████▄   ▄▄█████▄  ██▄████▄
#  ██▀  ▀██     ██       ██         ██     ██▀  ▀██  ██▀   ██  ██▀  ▀██   ██▀      ██▄▄▄▄██             ██▀      ██▄▄▄▄██    ██       ██▀      ██▄▄▄▄██  ██▄▄▄▄ ▀  ██▀   ██
#  ██    ██     ██       ██         ██     ██    ██  ██    ██  ██    ██   ██       ██▀▀▀▀▀▀   █████     ██       ██▀▀▀▀▀▀    ██       ██       ██▀▀▀▀▀▀   ▀▀▀▀██▄  ██    ██
#  ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄   ▄▄▄██▄▄▄  ▀██▄▄███  ██    ██  ▀██▄▄██▀   ██       ▀██▄▄▄▄█             ██       ▀██▄▄▄▄█    ██       ██       ▀██▄▄▄▄█  █▄▄▄▄▄██  ██    ██
#   ▄▀▀▀ ██  ▀▀▀▀▀▀▀▀     ▀▀▀▀   ▀▀▀▀▀▀▀▀   ▄▀▀▀ ██  ▀▀    ▀▀    ▀▀▀▀     ▀▀         ▀▀▀▀▀              ▀▀         ▀▀▀▀▀     ▀▀       ▀▀         ▀▀▀▀▀    ▀▀▀▀▀▀   ▀▀    ▀▀
#   ▀████▀▀                                 ▀████▀▀
#
# --- DESCRIPTION --- #
# Refreshes Git repository by removing cached files and recommitting to apply updated .gitignore
# --- DEPENDENCIES --- #
# - git
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
is-git-repo

git rm -r --cached .

git add .

git commit -am "remove ignored files $(now)"
