#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#     ██                                             ▄▄▄▄      ▄▄▄▄
#     ▀▀                           ██                ▀▀██      ▀▀██                                      ██
#   ████     ██▄████▄  ▄▄█████▄  ███████    ▄█████▄    ██        ██                 ▄████▄   ▀██  ██▀  ███████
#     ██     ██▀   ██  ██▄▄▄▄ ▀    ██       ▀ ▄▄▄██    ██        ██                ██▄▄▄▄██    ████      ██
#     ██     ██    ██   ▀▀▀▀██▄    ██      ▄██▀▀▀██    ██        ██       █████    ██▀▀▀▀▀▀    ▄██▄      ██
#  ▄▄▄██▄▄▄  ██    ██  █▄▄▄▄▄██    ██▄▄▄   ██▄▄▄███    ██▄▄▄     ██▄▄▄             ▀██▄▄▄▄█   ▄█▀▀█▄     ██▄▄▄
#  ▀▀▀▀▀▀▀▀  ▀▀    ▀▀   ▀▀▀▀▀▀      ▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀      ▀▀▀▀               ▀▀▀▀▀   ▀▀▀  ▀▀▀     ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Installs VS Code extensions from .vsix files in a specified directory
# --- DEPENDENCIES --- #
# - code
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
directory="${argv[0]:-extensions}"

# Change to the extensions directory
cd "${directory}" || log-error "directory '${directory}' was not found!"

shopt -s nullglob
extensions=(*.vsix)

if ((${#extensions[@]} == 0)); then
  log-error "No .vsix files found in ${directory}."
else
  # Loop through all .vsix files in the extensions directory
  for extension in "${extensions[@]}"; do
    # Install the extension using VSCode CLI
    code --install-extension "${extension}" || log-warning "Failed to install ${extension}."
  done
fi

log-success "Installation Done 🚀"
