#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#     ██                                      ██
#     ▀▀                                      ▀▀       ██
#   ████     ▄▄█████▄             ▄███▄██   ████     ███████              ██▄████   ▄████▄   ██▄███▄    ▄████▄
#     ██     ██▄▄▄▄ ▀            ██▀  ▀██     ██       ██                 ██▀      ██▄▄▄▄██  ██▀  ▀██  ██▀  ▀██
#     ██      ▀▀▀▀██▄   █████    ██    ██     ██       ██       █████     ██       ██▀▀▀▀▀▀  ██    ██  ██    ██
#  ▄▄▄██▄▄▄  █▄▄▄▄▄██            ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄              ██       ▀██▄▄▄▄█  ███▄▄██▀  ▀██▄▄██▀
#  ▀▀▀▀▀▀▀▀   ▀▀▀▀▀▀              ▄▀▀▀ ██  ▀▀▀▀▀▀▀▀     ▀▀▀▀              ▀▀         ▀▀▀▀▀   ██ ▀▀▀      ▀▀▀▀
#                                 ▀████▀▀                                                    ██
#
# --- DESCRIPTION --- #
# Checks if the current directory is a Git repository and not inside a .git directory
# --- DEPENDENCIES --- #
# - git
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/helpers.sh")"
eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "s" "safe" "Wether to exit with non-zero code or to kill the parent process as well"
cmdarg_parse "$@"
# ---  Main script logic --- #
isSafe="${cmdarg_cfg['safe']}"

if "${isSafe}"; then
  action='log-error --no-kill'
else
  action='log-error'
fi

# returns true if it's a git repo and false otherwise
isGitRepo="$(git rev-parse --is-inside-work-tree 2>/dev/null)" || "${action}" "$(pwd) is not a git repository."

# check if the user is inside .git directory
"${isGitRepo}" || "${action}" "Not in a work tree."

exit 0
