#!/usr/bin/env bash

set -euo pipefail

trap 'exit 1' SIGUSR1

# returns true if it's a git repo and false otherwise
isGitRepo=$(git rev-parse --is-inside-work-tree 2>/dev/null) || log-error "${PWD} is not a git repository."

# check if the user is inside .git directory
[[ ${isGitRepo} != true ]] && log-error "Not in a work tree."

exit 0
