#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#     ██                  ██
#     ▀▀                  ▀▀
#   ████      ▄████▄    ████     ██▄████▄   ▄█████▄   ██▄████   ██▄████
#     ██     ██▀  ▀██     ██     ██▀   ██   ▀ ▄▄▄██   ██▀       ██▀
#     ██     ██    ██     ██     ██    ██  ▄██▀▀▀██   ██        ██
#     ██     ▀██▄▄██▀  ▄▄▄██▄▄▄  ██    ██  ██▄▄▄███   ██        ██
#     ██       ▀▀▀▀    ▀▀▀▀▀▀▀▀  ▀▀    ▀▀   ▀▀▀▀ ▀▀   ▀▀        ▀▀
#  ████▀
#
# --- DESCRIPTION --- #
# Joins text using a given separator
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

# ---  Main script logic --- #
# Check for separator argument
if [[ $# -lt 1 ]]; then
  log-error "Separator is required\nUsage: $0 <separator> <array...>"
fi

# Set the separator and shift it off
separator="$1"
shift

# Join and output elements without trailing newline
[[ $# -gt 0 ]] && {
  # Remove the last occurance of the separator
  printf "%s${separator}" "${@}" | sed "s/\(.*\)${separator}/\1/"
  printf '\n'
}

exit 0
