#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄           ██     ▄▄▄▄      ▄▄▄▄                             ██
#  ██           ▀▀     ▀▀██      ▀▀██                             ▀▀       ██
#  ██ ▄██▀    ████       ██        ██     ██      ██  ▄█████▄   ████     ███████
#  ██▄██        ██       ██        ██     ▀█  ██  █▀  ▀ ▄▄▄██     ██       ██
#  ██▀██▄       ██       ██        ██      ██▄██▄██  ▄██▀▀▀██     ██       ██
#  ██  ▀█▄   ▄▄▄██▄▄▄    ██▄▄▄     ██▄▄▄   ▀██  ██▀  ██▄▄▄███  ▄▄▄██▄▄▄    ██▄▄▄
#  ▀▀   ▀▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀      ▀▀▀▀    ▀▀  ▀▀    ▀▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Kills and waits a proccess to finish
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #
trap 'exit 1' SIGUSR1
# ---  Main script logic --- #
pid="$1"
set +e
kill "${pid}" 2>/dev/null || true
wait "${pid}" 2>/dev/null || true

exit 0
