#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄           ██     ▄▄▄▄      ▄▄▄▄                             ██
#  ██           ▀▀     ▀▀██      ▀▀██                             ▀▀       ██
#  ██ ▄██▀    ████       ██        ██     ██      ██  ▄█████▄   ████     ███████
#  ██▄██        ██       ██        ██     ▀█  ██  █▀  ▀ ▄▄▄██     ██       ██
#  ██▀██▄       ██       ██        ██      ██▄██▄██  ▄██▀▀▀██     ██       ██
#  ██  ▀█▄   ▄▄▄██▄▄▄    ██▄▄▄     ██▄▄▄   ▀██  ██▀  ██▄▄▄███  ▄▄▄██▄▄▄    ██▄▄▄
#  ▀▀   ▀▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀      ▀▀▀▀    ▀▀  ▀▀    ▀▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Kills and waits a proccess to finish
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #
trap 'exit 1' SIGUSR1
# ---  Main script logic --- #
force=0
if [[ "$1" =~ --force|-f ]]; then
  shift
  force=1
fi

pid="$1"

if ((force)); then
  # Sends SIGKILL, a forceful, immediate termination signal.
  kill -9 "${pid}" 2>/dev/null || true
else
  # Sends SIGTERM, a polite request to the process to terminate.
  kill "${pid}" 2>/dev/null || true
fi

wait "${pid}" 2>/dev/null || true

sleep 0.25 && exit 0
