#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄▄▄                                ▄▄               ▄▄▄▄
#  ▀▀██                                ██              ██▀▀▀                         ██
#    ██       ▄████▄    ▄█████▄   ▄███▄██            ███████    ▄████▄   ██▄████▄  ███████   ▄▄█████▄
#    ██      ██▀  ▀██   ▀ ▄▄▄██  ██▀  ▀██              ██      ██▀  ▀██  ██▀   ██    ██      ██▄▄▄▄ ▀
#    ██      ██    ██  ▄██▀▀▀██  ██    ██   █████      ██      ██    ██  ██    ██    ██       ▀▀▀▀██▄
#    ██▄▄▄   ▀██▄▄██▀  ██▄▄▄███  ▀██▄▄███              ██      ▀██▄▄██▀  ██    ██    ██▄▄▄   █▄▄▄▄▄██
#     ▀▀▀▀     ▀▀▀▀     ▀▀▀▀ ▀▀    ▀▀▀ ▀▀              ▀▀        ▀▀▀▀    ▀▀    ▀▀     ▀▀▀▀    ▀▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Moves TTF and OTF fonts from ~/fonts to system font directories and refreshes the font cache
# --- DEPENDENCIES --- #
# - fd | fdfind (fd-find)
# - gum
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
cd "${HOME}/fonts" || log-error "failed to find '${HOME}/fonts' directory, create it first."

ttfDir="/usr/local/share/fonts/TTF"
otfDir="/usr/local/share/fonts/OTF"

[[ ! -d "${ttfDir}" ]] && sudo mkdir -p "${ttfDir}"

[[ ! -d "${otfDir}" ]] && sudo mkdir -p "${otfDir}"

sudo mv -i ./*.ttf "${ttfDir}" >/dev/null 2>&1 || printf ''
sudo mv -i ./*.otf "${otfDir}" >/dev/null 2>&1 || printf ''

fd . -t d -d 1 | while read -r dir; do
  ttfDirs=($(fd . -e ttf "${dir}" -x dirname {} | no-dups -a))
  if [[ ${#ttfDirs} -gt 0 ]]; then
    sudo mv "${ttfDirs[@]}" -t "${ttfDir}" &&
      log-info "Moved $(echo "${ttfDirs[@]}" | tr " " "\n" | cut -d " " -f 5- | tr "\n" " " | trim)"
  fi

  if [[ -d "${dir}" ]]; then
    otfDirs=($(fd . -e otf "${dir}" -x dirname {} | no-dups -a))
    if [[ ${#otfDirs} -gt 0 ]]; then
      sudo mv "${otfDirs[@]}" -t "${otfDir}" &&
        log-info "Moved $(echo "${otfDirs[@]}" | tr " " "\n" | cut -d " " -f 5- | tr "\n" " " | trim)"
    fi
  fi
done

gum spin --title "Caching fonts..." --spinner "dot" -- sudo fc-cache -r

log-success "Fonts reloaded succefully!"
