#!/usr/bin/env bash
# shellcheck disable=SC2207

set -euo pipefail

ttfDir="/usr/local/share/fonts/TTF"
otfDir="/usr/local/share/fonts/OTF"

[[ ! -d "${ttfDir}" ]] && sudo mkdir -p "${ttfDir}"

[[ ! -d "${otfDir}" ]] && sudo mkdir -p "${otfDir}"

cd ~/fonts || log-error "failed to find '~/fonts' directory"

sudo mv -i ./*.ttf "${ttfDir}" >/dev/null 2>&1 || printf ''
sudo mv -i ./*.otf "${otfDir}" >/dev/null 2>&1 || printf ''

fd . -t d -d 1 | while read -r dir; do
  ttfDirs=($(fd . -e ttf "${dir}" -x dirname {} | no-dups -s))
  if [[ ${#ttfDirs} -gt 0 ]]; then
    sudo mv "${ttfDirs[@]}" -t "${ttfDir}" &&
      log-info "Moved $(echo "${ttfDirs[@]}" | tr " " "\n" | cut -d " " -f 5- | tr "\n" " " | trim)"
  fi

  if [[ -d "${dir}" ]]; then
    otfDirs=($(fd . -e otf "${dir}" -x dirname {} | no-dups -s))
    if [[ ${#otfDirs} -gt 0 ]]; then
      sudo mv "${otfDirs[@]}" -t "${otfDir}" &&
        log-info "Moved $(echo "${otfDirs[@]}" | tr " " "\n" | cut -d " " -f 5- | tr "\n" " " | trim)"
    fi
  fi
done

gum spin --title "Caching fonts..." --spinner "dot" -- sudo fc-cache -r

log-success "Fonts reloaded succefully!"
