#!/usr/bin/env bash

# shellcheck source=/dev/null
source logs.sh

if [[ ! -d "/usr/share/fonts/TTF" ]]; then
	sudo mkdir /usr/share/fonts/TTF/
fi

if [[ ! -d "/usr/share/fonts/OTF" ]]; then
	sudo mkdir /usr/share/fonts/OTF/
fi

sudo mv ~/fonts/*.ttf /usr/share/fonts/TTF/ >/dev/null 2>&1 || log-warning "No .ttf fonts found!"
sudo mv ~/fonts/*.otf /usr/share/fonts/OTF/ >/dev/null 2>&1 || log-warning "No .otf fonts found!"

log-info "Caching fonts..."

sudo fc-cache -f && log-success "Fonts reloaded succefully!"
