#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
# ▄▄▄▄                                       ██                  ▄▄▄▄
# ▀▀██                                       ▀▀                 ██▀▀▀
#   ██       ▄████▄    ▄███▄██             ████     ██▄████▄  ███████    ▄████▄
#   ██      ██▀  ▀██  ██▀  ▀██               ██     ██▀   ██    ██      ██▀  ▀██
#   ██      ██    ██  ██    ██   █████       ██     ██    ██    ██      ██    ██
#   ██▄▄▄   ▀██▄▄██▀  ▀██▄▄███            ▄▄▄██▄▄▄  ██    ██    ██      ▀██▄▄██▀
#    ▀▀▀▀     ▀▀▀▀     ▄▀▀▀ ██            ▀▀▀▀▀▀▀▀  ▀▀    ▀▀    ▀▀        ▀▀▀▀
#                      ▀████▀▀
#
# --- DESCRIPTION --- #
# Prints info messages in purple with a '[INFO] ' prefix; reads from stdin or arguments
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/helpers.sh")"
source "$(include "check-deps")"

checkDeps "$0"
# ---  Main script logic --- #
if [[ "$1" =~ ^-n$ ]]; then
  shift || true
  log.sh "INFO" -n "$(input "$@")"
else
  log.sh "INFO" "$(input "$@")"
fi
