#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄▄▄                                          ▄▄            ▄▄
#  ▀▀██                                          ██            ██
#    ██       ▄████▄    ▄███▄██             ▄███▄██   ▄████▄   ██▄███▄   ██    ██   ▄███▄██
#    ██      ██▀  ▀██  ██▀  ▀██            ██▀  ▀██  ██▄▄▄▄██  ██▀  ▀██  ██    ██  ██▀  ▀██
#    ██      ██    ██  ██    ██   █████    ██    ██  ██▀▀▀▀▀▀  ██    ██  ██    ██  ██    ██
#    ██▄▄▄   ▀██▄▄██▀  ▀██▄▄███            ▀██▄▄███  ▀██▄▄▄▄█  ███▄▄██▀  ██▄▄▄███  ▀██▄▄███
#     ▀▀▀▀     ▀▀▀▀     ▄▀▀▀ ██              ▀▀▀ ▀▀    ▀▀▀▀▀   ▀▀ ▀▀▀     ▀▀▀▀ ▀▀   ▄▀▀▀ ██
#                       ▀████▀▀                                                     ▀████▀▀
#
# --- DESCRIPTION --- #
# Prints debug messages in magenta with a '[DEBUG] ' prefix; reads from stdin or arguments
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/helpers.sh")"
source "$(include "check-deps")"

checkDeps "$0"
# ---  Main script logic --- #
if [[ "$1" =~ ^-n$ ]]; then
  shift || true
  log.sh "DEBUG" -n "$(input "$@")"
else
  log.sh "DEBUG" "$(input "$@")"
fi
