#!/usr/bin/env bash
# --- SCRIPT SIGNATURE --- #
#
# ▄▄▄▄                                       ██                  ▄▄▄▄
# ▀▀██                                       ▀▀                 ██▀▀▀
#   ██       ▄████▄    ▄███▄██             ████     ██▄████▄  ███████    ▄████▄
#   ██      ██▀  ▀██  ██▀  ▀██               ██     ██▀   ██    ██      ██▀  ▀██
#   ██      ██    ██  ██    ██   █████       ██     ██    ██    ██      ██    ██
#   ██▄▄▄   ▀██▄▄██▀  ▀██▄▄███            ▄▄▄██▄▄▄  ██    ██    ██      ▀██▄▄██▀
#    ▀▀▀▀     ▀▀▀▀     ▄▀▀▀ ██            ▀▀▀▀▀▀▀▀  ▀▀    ▀▀    ▀▀        ▀▀▀▀
#                      ▀████▀▀
#
# --- DESCRIPTION --- #
# Prints blue info text
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

# black: 0, red: 1, green: 2, yellow: 3,
# blue: 4, magenta: 5, cyan: 6, white: 7

tput setaf 4

echo -e "[INFO]: $*"

tput sgr0
