#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄▄▄                                                                               ██
#  ▀▀██                                                                               ▀▀
#    ██       ▄████▄    ▄███▄██           ██      ██  ▄█████▄   ██▄████  ██▄████▄   ████     ██▄████▄   ▄███▄██
#    ██      ██▀  ▀██  ██▀  ▀██           ▀█  ██  █▀  ▀ ▄▄▄██   ██▀      ██▀   ██     ██     ██▀   ██  ██▀  ▀██
#    ██      ██    ██  ██    ██   █████    ██▄██▄██  ▄██▀▀▀██   ██       ██    ██     ██     ██    ██  ██    ██
#    ██▄▄▄   ▀██▄▄██▀  ▀██▄▄███            ▀██  ██▀  ██▄▄▄███   ██       ██    ██  ▄▄▄██▄▄▄  ██    ██  ▀██▄▄███
#     ▀▀▀▀     ▀▀▀▀     ▄▀▀▀ ██             ▀▀  ▀▀    ▀▀▀▀ ▀▀   ▀▀       ▀▀    ▀▀  ▀▀▀▀▀▀▀▀  ▀▀    ▀▀   ▄▀▀▀ ██
#                       ▀████▀▀                                                                         ▀████▀▀
#
# --- DESCRIPTION --- #
# Prints warning messages in yellow with a '[WARNING] ' prefix; reads from stdin or arguments
# --- DEPENDENCIES --- #
# - tput
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/helpers.sh")"
# ---  Main script logic --- #

# read from stdin
str="$(input "$@")"

printYellow "[WARNING] ${str}"
