#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#  ▄▄▄▄
#  ▀▀██
#    ██       ▄████▄    ▄███▄██             ▄████▄    ██▄████   ██▄████   ▄████▄    ██▄████
#    ██      ██▀  ▀██  ██▀  ▀██            ██▄▄▄▄██   ██▀       ██▀      ██▀  ▀██   ██▀
#    ██      ██    ██  ██    ██   █████    ██▀▀▀▀▀▀   ██        ██       ██    ██   ██
#    ██▄▄▄   ▀██▄▄██▀  ▀██▄▄███            ▀██▄▄▄▄█   ██        ██       ▀██▄▄██▀   ██
#     ▀▀▀▀     ▀▀▀▀     ▄▀▀▀ ██              ▀▀▀▀▀    ▀▀        ▀▀         ▀▀▀▀     ▀▀
#                       ▀████▀▀
#
# --- DESCRIPTION --- #
# Prints error messages in red with a '[ERROR] ' prefix to stderr, signals parent with SIGUSR1, and exits with failure
# --- DEPENDENCIES --- #
# - tput
# - ps
# - xargs
# - kill
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/helpers.sh")"
# ---  Main script logic --- #

# read from stdin
str="$(input "$@")"

# Print error message in red
printRed "[ERROR] ${str}" 1>&2

# Get parent PID (script that called log-error) and send SIGUSR1
PARENT_PID=$(ps -o ppid= $$ | xargs)
kill -SIGUSR1 "${PARENT_PID}"

# Exit with failure code (fallback if signal is ignored)
exit 1
