#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄▄▄                                              ▄▄▄▄
#  ▀▀██                                              ▀▀██
#    ██      ▄▄█████▄             ▄█████▄   ▄████▄     ██       ▄████▄    ██▄████  ▄▄█████▄
#    ██      ██▄▄▄▄ ▀            ██▀    ▀  ██▀  ▀██    ██      ██▀  ▀██   ██▀      ██▄▄▄▄ ▀
#    ██       ▀▀▀▀██▄   █████    ██        ██    ██    ██      ██    ██   ██        ▀▀▀▀██▄
#    ██▄▄▄   █▄▄▄▄▄██            ▀██▄▄▄▄█  ▀██▄▄██▀    ██▄▄▄   ▀██▄▄██▀   ██       █▄▄▄▄▄██
#     ▀▀▀▀    ▀▀▀▀▀▀               ▀▀▀▀▀     ▀▀▀▀       ▀▀▀▀     ▀▀▀▀     ▀▀        ▀▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Parses exported color variables from a Zsh config and displays their names with the corresponding color
# --- DEPENDENCIES --- #
# - rg (ripgrep)
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/helpers.sh")"
source "$(include "lib/cmdarg.sh")"
source "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
declare -a colors

findColors() {
  {
    if [[ -f "${ZDOTDIR}/variables.sh" ]]; then
      rg -o 'U_[A-Za-z0-9_]*=.*' "${ZDOTDIR}/variables.sh" | tr -d '"'
    fi
    printenv
  } | no-dups | rg --color=never '^U_'
  return 0
}

mapfile -t colors < <(findColors)

for line in "${colors[@]}"; do
  varname="${line%%=*}"
  color="${line#*=}"
  isHex "${color}" || continue
  printHex "${color}" "${varname} ${color}"
done
