#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#  ▄▄▄▄                                              ▄▄▄▄
#  ▀▀██                                              ▀▀██
#    ██      ▄▄█████▄             ▄█████▄   ▄████▄     ██       ▄████▄    ██▄████  ▄▄█████▄
#    ██      ██▄▄▄▄ ▀            ██▀    ▀  ██▀  ▀██    ██      ██▀  ▀██   ██▀      ██▄▄▄▄ ▀
#    ██       ▀▀▀▀██▄   █████    ██        ██    ██    ██      ██    ██   ██        ▀▀▀▀██▄
#    ██▄▄▄   █▄▄▄▄▄██            ▀██▄▄▄▄█  ▀██▄▄██▀    ██▄▄▄   ▀██▄▄██▀   ██       █▄▄▄▄▄██
#     ▀▀▀▀    ▀▀▀▀▀▀               ▀▀▀▀▀     ▀▀▀▀       ▀▀▀▀     ▀▀▀▀     ▀▀        ▀▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Parses exported color variables from a Zsh config and displays their names with the corresponding color
# --- DEPENDENCIES --- #
# - rg (ripgrep)
# - awk
# - tr
# - gum
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
declare -a colors

mapfile -t colors < <(rg -N "export U_" "${TUCKR_DIR}/zsh/.config/zsh/variables.zsh")

for line in "${colors[@]}"; do
  var=$(echo "${line}" | awk '{print $2}')
  varname=$(echo "${var}" | awk -F "=" '{print $1}')
  color=$(echo "${var}" | awk -F "=" '{print $2}' | tr -d '"')

  gum style --foreground="${color}" "${varname} ${color}"
done
