#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                      ▄▄                                         ██
#                      ██                                         ▀▀                                     ██
#  ████▄██▄   ▄█████▄  ██ ▄██▀    ▄████▄             ▄▄█████▄   ████      ▄███▄██  ██▄████▄   ▄█████▄  ███████   ██    ██   ██▄████   ▄████▄
#  ██ ██ ██   ▀ ▄▄▄██  ██▄██     ██▄▄▄▄██            ██▄▄▄▄ ▀     ██     ██▀  ▀██  ██▀   ██   ▀ ▄▄▄██    ██      ██    ██   ██▀      ██▄▄▄▄██
#  ██ ██ ██  ▄██▀▀▀██  ██▀██▄    ██▀▀▀▀▀▀   █████     ▀▀▀▀██▄     ██     ██    ██  ██    ██  ▄██▀▀▀██    ██      ██    ██   ██       ██▀▀▀▀▀▀
#  ██ ██ ██  ██▄▄▄███  ██  ▀█▄   ▀██▄▄▄▄█            █▄▄▄▄▄██  ▄▄▄██▄▄▄  ▀██▄▄███  ██    ██  ██▄▄▄███    ██▄▄▄   ██▄▄▄███   ██       ▀██▄▄▄▄█
#  ▀▀ ▀▀ ▀▀   ▀▀▀▀ ▀▀  ▀▀   ▀▀▀    ▀▀▀▀▀              ▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀   ▄▀▀▀ ██  ▀▀    ▀▀   ▀▀▀▀ ▀▀     ▀▀▀▀    ▀▀▀▀ ▀▀   ▀▀         ▀▀▀▀▀
#                                                                         ▀████▀▀
#
# --- DESCRIPTION --- #
# Generates a standardized script signature block with ASCII title, description, and dependency list using toilet
# --- DEPENDENCIES --- #
# - toilet
# - sed
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
name="$1"
desc="$2"
deps="$3"

echo "#!/usr/bin/env bash"
echo ""
echo "# --- SCRIPT SIGNATURE --- #"

toilet --font mono12 --termwidth --width 190 "${name}" | sed 's/^/# /'

echo "# --- DESCRIPTION --- #"
echo "# ${desc}"
echo "# --- DEPENDENCIES --- #"

if [[ -z "${deps}" ]]; then
  echo "#"
else
  for dep in ${deps}; do
    echo "# - ${dep}"
  done
fi

echo "# --- END SIGNATURE --- #"
echo ""

echo "set -euo pipefail"
echo ""
echo "trap 'exit 1' SIGUSR1"
echo ""
echo "check-deps \"$0\""
# ---  Main script logic --- #"
echo ""
