#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                      ▄▄                                         ██
#                      ██                                         ▀▀                                     ██
#  ████▄██▄   ▄█████▄  ██ ▄██▀    ▄████▄             ▄▄█████▄   ████      ▄███▄██  ██▄████▄   ▄█████▄  ███████   ██    ██   ██▄████   ▄████▄
#  ██ ██ ██   ▀ ▄▄▄██  ██▄██     ██▄▄▄▄██            ██▄▄▄▄ ▀     ██     ██▀  ▀██  ██▀   ██   ▀ ▄▄▄██    ██      ██    ██   ██▀      ██▄▄▄▄██
#  ██ ██ ██  ▄██▀▀▀██  ██▀██▄    ██▀▀▀▀▀▀   █████     ▀▀▀▀██▄     ██     ██    ██  ██    ██  ▄██▀▀▀██    ██      ██    ██   ██       ██▀▀▀▀▀▀
#  ██ ██ ██  ██▄▄▄███  ██  ▀█▄   ▀██▄▄▄▄█            █▄▄▄▄▄██  ▄▄▄██▄▄▄  ▀██▄▄███  ██    ██  ██▄▄▄███    ██▄▄▄   ██▄▄▄███   ██       ▀██▄▄▄▄█
#  ▀▀ ▀▀ ▀▀   ▀▀▀▀ ▀▀  ▀▀   ▀▀▀    ▀▀▀▀▀              ▀▀▀▀▀▀   ▀▀▀▀▀▀▀▀   ▄▀▀▀ ██  ▀▀    ▀▀   ▀▀▀▀ ▀▀     ▀▀▀▀    ▀▀▀▀ ▀▀   ▀▀         ▀▀▀▀▀
#                                                                         ▀████▀▀
#
# --- DESCRIPTION --- #
# Generates a standardized script signature block with ASCII title, description, and dependency list using toilet
# --- DEPENDENCIES --- #
# - toilet
# - sed
# - printf
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
name="$1"
desc="$2"
deps="$3"

cat <<EOF
#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
$(toilet --font mono12 --termwidth --width 190 "${name}" | sed 's/^/# /')
# --- DESCRIPTION --- #
# ${desc}
# --- DEPENDENCIES --- #
EOF

if [[ -z "${deps}" ]]; then
  echo "#"
else
  for dep in ${deps}; do
    echo "# - ${dep}"
  done
fi

cat <<'EOF'
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/helpers.sh")"

eval "$(include "check-deps")"
checkDeps "$0"

# ---  Main script logic --- #


EOF
