#!/usr/bin/env bash

set -euo pipefail

trap 'exit 1' SIGUSR1

name="$1"
desc="$2"
deps="$3"

echo "#!/usr/bin/env bash"
echo ""
echo "# --- SCRIPT SIGNATURE --- #"

toilet --font mono12 --termwidth "${name}" | sed 's/^/# /'

echo "# --- DESCRIPTION --- #"
echo "# ${desc}"
echo "# --- DEPENDENCIES --- #"

if [[ -z "${deps}" ]]; then
  echo "#"
else
  for dep in ${deps}; do
    echo "# - ${dep}"
  done
fi

echo "# --- END SIGNATURE --- #"
echo ""

echo "set -euo pipefail"
echo ""
echo "trap 'exit 1' SIGUSR1"
echo ""
echo "# ---  Main script logic --- #"
echo ""
