#!/usr/bin/env bash

# shellcheck source=/dev/null
source logs.sh

file="$1"

if [[ -f "$file" ]]; then
  # shellcheck disable=SC2001
  filename="$(echo "$file" | sed 's/\.[^.]*$//')"

  pandoc "$file" -o "${filename}.docx" --reference-doc="$MRT" || log-error "an Error occured"

  log-success "$file converted successfully!"

else
  log-error "File $file does not exist!"
fi
