#!/usr/bin/env bash

# shellcheck source=/dev/null
source logs.sh

file="$1"

if [[ -f "$file" ]]; then
  filename="$(echo "$file" | sed 's/\.[^.]*$//')"

  pandoc "$file" -o "${filename}.docx" --reference-doc="$MRT" || log_error "an Error occured"

  log_info "$file converted successfully!"

else 
  log_error "File $file does not exist!"
fi


