#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                  ▄▄     ▄▄▄▄
#                  ██    ██▀▀▀               ██
#  ████▄██▄   ▄███▄██  ███████   ████▄██▄  ███████
#  ██ ██ ██  ██▀  ▀██    ██      ██ ██ ██    ██
#  ██ ██ ██  ██    ██    ██      ██ ██ ██    ██
#  ██ ██ ██  ▀██▄▄███    ██      ██ ██ ██    ██▄▄▄
#  ▀▀ ▀▀ ▀▀    ▀▀▀ ▀▀    ▀▀      ▀▀ ▀▀ ▀▀     ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Formats Markdown files using Prettier; auto-discovers files with fd or formats given .md/.markdown files
# --- DEPENDENCIES --- #
# - fd | fdfind (fd-find)
# - awk
# - prettier
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"
checkDeps "$0"

cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
declare -a files

if [[ "${argv[0]}" == "." ]] || ((argc == 0)); then
  # Populate the array directly from fd output
  mapfile -t files < <(fd . -e md -e markdown --hidden)
else
  for file in "${argv[@]}"; do
    ext=$(echo "${file}" | awk -F. '{print $NF}')
    [[ "${ext}" == "md" || "${ext}" == "markdown" ]] && files+=("${file}")
  done
fi

# NOTE: ((0)) fails, while any other number succeeds
((${#files[@]})) || log-error "No valid markdown files were passed"

for file in "${files[@]}"; do
  mdclean "${file}" --quiet || log-warning "Failed to clean '${file}'"

  sed -e "s|[‘’]|'|g" \
    -e 's|[“”]|"|g' \
    -i "${file}"
done

prettier --write --config "${PRETTIERRC}" "${files[@]}"
