#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                  ▄▄     ▄▄▄▄
#                  ██    ██▀▀▀               ██
#  ████▄██▄   ▄███▄██  ███████   ████▄██▄  ███████
#  ██ ██ ██  ██▀  ▀██    ██      ██ ██ ██    ██
#  ██ ██ ██  ██    ██    ██      ██ ██ ██    ██
#  ██ ██ ██  ▀██▄▄███    ██      ██ ██ ██    ██▄▄▄
#  ▀▀ ▀▀ ▀▀    ▀▀▀ ▀▀    ▀▀      ▀▀ ▀▀ ▀▀     ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Formats Markdown files using Prettier; auto-discovers files with fd or formats given .md/.markdown files
# --- DEPENDENCIES --- #
# - fd | fdfind (fd-find)
# - awk
# - prettier
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/cmdarg.sh")"
source "$(include "check-deps")"
checkDeps "$0"

cmdarg_info "header" "$(get-desc "$0")"
cmdarg "j?" "jobs" "How many threads to use in parallel?" "$(nproc)"
cmdarg_parse "$@"
# ---  Main script logic --- #
jobs="${cmdarg_cfg['jobs']}"
isPositive "${jobs}" || log-error "Number of threads must be positive"

declare -a files
if ((argc == 0)); then
  # Populate the array directly from fd output
  mapfile -t files < <(fd.sh . -I -e md -e markdown .)
else
  for arg in "${argv[@]}"; do
    if [[ -d "${arg}" ]]; then
      # Populate the array directly from fd output
      mapfile -t _files < <(fd.sh . -I -e md -e markdown "${arg}")
      files+=("${_files[@]}")
    else
      [[ "${arg##*.}" =~ ^(md|markdown)$ ]] && files+=("${arg}")
    fi
  done
fi

filesCount=${#files[@]}
((0 < filesCount)) || log-error "No valid markdown files were passed"

spinner.sh "Formatting ${filesCount} files..." 1>&2 &
SPINNER_PID=$!

mdmath -q -j "${jobs}" "${files[@]}" || log-warning "Failed to fix math in ${filesCount} files"
mdclean -q -j "${jobs}" "${files[@]}" || log-warning "Failed to clean ${filesCount} files"

killwait "${SPINNER_PID}"

prettier --write \
  --ignore-path '/dev/null' \
  --ignore-unknown='false' \
  --config "${PRETTIERRC}" "${files[@]}"
