#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                  ▄▄                                ▄▄
#                  ██                        ██      ██
#  ████▄██▄   ▄███▄██  ████▄██▄   ▄█████▄  ███████   ██▄████▄
#  ██ ██ ██  ██▀  ▀██  ██ ██ ██   ▀ ▄▄▄██    ██      ██▀   ██
#  ██ ██ ██  ██    ██  ██ ██ ██  ▄██▀▀▀██    ██      ██    ██
#  ██ ██ ██  ▀██▄▄███  ██ ██ ██  ██▄▄▄███    ██▄▄▄   ██    ██
#  ▀▀ ▀▀ ▀▀    ▀▀▀ ▀▀  ▀▀ ▀▀ ▀▀   ▀▀▀▀ ▀▀     ▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Replaces LaTeX math delimiters with Obsidian's delimiters in a given file
# Usage: mdmath <files>
# --- DEPENDENCIES --- #
# - grep
# - parallel
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "lib/helpers.sh")"
eval "$(include "check-deps")"

checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "q" "quiet" "Supress output"
cmdarg_parse "$@"
# ---  Main script logic --- #
# Check if the correct number of arguments is passed
if ! ((argc)); then
  cmdarg_usage
  exit 1
fi

isQuiet="${cmdarg_cfg['quiet']}"

# Count occurrences of all delimiters to be replaced
get_total_count() {
  grep -hc "$1" "${argv[@]}" 2>/dev/null | awk '{s+=$1} END {print s}' || printf '0'
}

total_count_display=$(get_total_count '\\\[' | tr -d '\n')
total_count_inline=$(get_total_count '\\(' | tr -d '\n')
total_count=$((total_count_display + total_count_inline))

main() {
  local file count count_display count_inline
  for file in "$@"; do
    # Check if the file exists
    if [[ ! -f ${file} ]]; then
      log-warning "File '${file}' was not found!"
      continue
    fi

    count_display=$(grep -c '\\\[' "${file}" || true)
    count_inline=$(grep -c '\\(' "${file}" || true)
    count=$((count_display + count_inline))

    if ! ((count)); then
      "${isQuiet}" || log-info "Nothing to do!"
      continue
    fi

    # Perform the replacements
    sed -i -e 's~\\\[~$$~g' \
      -e 's~\\\]~$$~g' \
      -e 's~ \\)~$~g' \
      -e 's~\\( ~$~g' \
      -e 's~\\(~$~g' \
      -e 's~\\)~$~g' "${file}"
  done
}

export -f main
export isQuiet

printf '%s\0' "${argv[@]}" | parallel -0 -j "$(nproc)" -k -m --tty main

"${isQuiet}" || log-success "${total_count} Replacements made"
