#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                                         ▄▄▄▄
#            ██                                        ██▀▀▀
#  ████▄██▄  ██ ▄██▀    ▄█████▄   ▄████▄   ██▄████▄  ███████
#  ██ ██ ██  ██▄██     ██▀    ▀  ██▀  ▀██  ██▀   ██    ██
#  ██ ██ ██  ██▀██▄    ██        ██    ██  ██    ██    ██
#  ██ ██ ██  ██  ▀█▄   ▀██▄▄▄▄█  ▀██▄▄██▀  ██    ██    ██
#  ▀▀ ▀▀ ▀▀  ▀▀   ▀▀▀    ▀▀▀▀▀     ▀▀▀▀    ▀▀    ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Creates or moves configuration directories for an app; interacts with the user to confirm actions and manage directories
# --- DEPENDENCIES --- #
# - gum
# - tuckr
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/helpers.sh")"

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
app=$1
[[ -z ${app} ]] && app=$(gum input --placeholder "Enter app's name e.g. vim")

target="${TUCKR_DIR}/${app}/.config/${app}"

source="${XDG_CONFIG_HOME:-"${HOME}/.config"}/${app}"

if [[ ! -d "${source}" ]]; then

  if [[ ! -d "${target}" ]]; then # if !from && !to: mkdir to
    log-warning "Source directory doesn't exist!"
    createDist=$(gum confirm "Do you want to create the target directory?") || createDist=1

    if [[ ${createDist} -eq 0 ]]; then # 0 means yes
      mkdir -p "${target}"
    else
      terminate "No changes were made!"
    fi
  else # if !from && to: do nothing
    terminate "Directory '${target}' already exists!"
  fi
else
  if [[ ! -d "${target}" ]]; then # if from && !to: mkdir to
    mkdir -p "${target}"
    log-info "'${target}' directory created!"
  fi
  moveSource=$(gum confirm "Do you want to move exsiting files to the target directory?") ||
    terminate "No changes were made!"
  if [[ ${moveSource} -eq 0 ]]; then # 0 means yes
    target="$(dirname "${target}")"
    gum spin \
      --spinner dot \
      --title "Moving ${app}'s config from '$(dirname "${source}")' to '$(dirname "${target}")'" \
      -- mv -v "${source}" "${target}"
  fi
fi

log-success "Created config directory for ${app}!"

tuckr a "${app}" # Populate the config after making it
