#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                                      ▄▄
#            ██                              ██      ██
#  ████▄██▄  ██ ▄██▀   ██▄███▄   ▀██  ███  ███████   ██▄████▄   ▄████▄   ██▄████▄
#  ██ ██ ██  ██▄██     ██▀  ▀██   ██▄ ██     ██      ██▀   ██  ██▀  ▀██  ██▀   ██
#  ██ ██ ██  ██▀██▄    ██    ██    ████▀     ██      ██    ██  ██    ██  ██    ██
#  ██ ██ ██  ██  ▀█▄   ███▄▄██▀     ███      ██▄▄▄   ██    ██  ▀██▄▄██▀  ██    ██
#  ▀▀ ▀▀ ▀▀  ▀▀   ▀▀▀  ██ ▀▀▀       ██        ▀▀▀▀   ▀▀    ▀▀    ▀▀▀▀    ▀▀    ▀▀
#                      ██         ███
#
# --- DESCRIPTION --- #
# Creates a Python project using `uv` with a corresponding shell script wrapper.
# --- DEPENDENCIES --- #
# - fd | fdfind (fd-find)
# - uv
# - nano
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
dir="${SCRIPTS_DIR}/python"
name="${argv[0]}"

# Check if it ends with the .py extension
[[ "${name}" =~ (\.py)$ ]] || name="${name}.py"

nameNoExt="$(strip-ext "${name}" py)"
fileExists="$(fd-all "${nameNoExt}" -e py "${dir}")"
scriptExists=$(fd-all "${nameNoExt}" -d 1 "${SCRIPTS_DIR}")

if [[ -n "${fileExists}" ]]; then
  log-error "File ${name} already exists at ${fileExists}"
elif [[ -n "${scriptExists}" ]]; then
  log-error "Script ${nameNoExt} already exists at ${scriptExists}"
fi

projectDir="${dir}/${nameNoExt}"

mkdir -p "${projectDir}"
cd "${projectDir}" || log-error "Cannot cd into '${projectDir}'"

uv init --name "${nameNoExt}" --no-readme --no-workspace
uv venv # creates the venv

scriptPath="${SCRIPTS_DIR}/${nameNoExt}"

touch "${scriptPath}" || log-error "Failed to create file '${scriptPath}'"

scriptContent() {
  cat <<'EOF'
#!/usr/bin/env bash

runpy "$0" "$@"
EOF
}

scriptContent >"${scriptPath}" || log-error "Failed to write to file '${scriptPath}'"

chmod u+x "${scriptPath}" || log-error "Failed to make '${scriptPath}' executable"

renamefile "main.py" "${name}" &>/dev/null

"${EDITOR:-nano}" "${name}"

log-success "Script '${scriptPath}' created succefully!"
