#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                                         ██
#            ██                                         ▀▀                 ██
#  ████▄██▄  ██ ▄██▀   ▄▄█████▄   ▄█████▄   ██▄████   ████     ██▄███▄   ███████
#  ██ ██ ██  ██▄██     ██▄▄▄▄ ▀  ██▀    ▀   ██▀         ██     ██▀  ▀██    ██
#  ██ ██ ██  ██▀██▄     ▀▀▀▀██▄  ██         ██          ██     ██    ██    ██
#  ██ ██ ██  ██  ▀█▄   █▄▄▄▄▄██  ▀██▄▄▄▄█   ██       ▄▄▄██▄▄▄  ███▄▄██▀    ██▄▄▄
#  ▀▀ ▀▀ ▀▀  ▀▀   ▀▀▀   ▀▀▀▀▀▀     ▀▀▀▀▀    ▀▀       ▀▀▀▀▀▀▀▀  ██ ▀▀▀       ▀▀▀▀
#                                                              ██
#
# --- DESCRIPTION --- #
# Automatically creates bash scripts with optional flags for temporary or named files, and copies the script name to the clipboard if temporary
# --- DEPENDENCIES --- #
# - gum
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "t" "temp" "Creates the script at /tmp and copies its name to clipboard"
cmdarg "f?" "file" "Creates the script with the given name in the current working directory"
cmdarg "q" "quiet" "Supress stdout"
cmdarg_parse "$@"
# ---  Main script logic --- #
isTemp="${cmdarg_cfg['temp']}"
filename="${cmdarg_cfg['file']}"
quiet="${cmdarg_cfg['quiet']}"
no_flags='false'
file=""

{ ${isTemp} || [[ -n "${filename}" ]]; } || no_flags='true'

scriptContent() {
  cat <<'EOF'
#!/usr/bin/env bash

set -eo pipefail
trap 'exit 1' SIGUSR1

# ---  Main script logic --- #
EOF
}

validateAndCreateFile() {
  local file="$1"
  [[ -f "${file}" ]] && log-error "The script '$(basename "${file}")' already exists at '${file}'!"

  touch "${file}" || log-error "Failed to create file '${file}'"

  chmod u+x "${file}" || log-error "Failed to make '$(basename "${file}")' executable"
}

if "${isTemp}"; then
  file=$(mktemp -t XXXXX-script.sh)

  chmod u+x "${file}" || log-error "Failed to make '$(basename "${file}")' executable"

  name="${file}"
  clipcopy "${file}"
  scriptContent >"${file}"
  log-info "The script name was copied to clipboard"

elif "${no_flags}"; then
  if [[ -n ${argv[0]} ]]; then
    name=${argv[0]}
  else
    name="$(gum input --placeholder "Enter Script's name: ")" || log-error "Failed to capture the script name"
  fi
  file="${SCRIPTS_DIR}/${name}"

  validateAndCreateFile "${file}"

  mkdir -p "$(dirname "${file}")" 2>/dev/null
  name="$(basename "${file}")"
  make-signature "${name}" "" "" >"${file}"

elif [[ -z "${filename}" ]]; then
  name="$(gum input --placeholder "Enter Script's name: ")" || log-error "Failed to capture the script name"
  file="${PWD}/${name}"

  validateAndCreateFile "${file}"

  mkdir -p "$(dirname "${file}")" 2>/dev/null
  name="$(basename "${file}")"

  make-signature "${name}" "" "" >"${file}"

  if [[ "${name}" != *.sh ]]; then
    if gum confirm "Do you want to add .sh extension to your script?"; then
      rm -f "${file}"
      file="${PWD}/${name}.sh"
      validateAndCreateFile "${file}"
    fi
  fi

elif [[ -n "${filename}" ]]; then
  file="${PWD}/${filename}"

  validateAndCreateFile "${file}"

  mkdir -p "$(dirname "${file}")" 2>/dev/null
  name="$(basename "${file}")"

  if [[ "${name}" != *.sh ]]; then
    if gum confirm "Do you want to add .sh extension to your script?"; then
      rm -f "${file}"
      file="${PWD}/${name}.sh"
      validateAndCreateFile "${file}"
    fi
  fi

  scriptContent >"${file}"
fi

"${EDITOR}" "${file}"

"${quiet}" || log-success "Script '$(basename "${file}")' created succefully!"
