#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#
#
#  ████▄██▄  ██▄  ▄██  ██▄███▄
#  ██ ██ ██   ██  ██   ██▀  ▀██
#  ██ ██ ██   ▀█▄▄█▀   ██    ██
#  ██ ██ ██    ████    ███▄▄██▀
#  ▀▀ ▀▀ ▀▀     ▀▀     ██ ▀▀▀
#                      ██
#
# --- DESCRIPTION --- #
# Moves a file to a new location, creating the target directory if necessary
# --- DEPENDENCIES --- #
# - mkdir
# - mv
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "f" "force" "Overwrite without confirmation"
cmdarg "i" "interactive" "Confirm before overwriting"
cmdarg_parse "$@"
# ---  Main script logic --- #
force="${cmdarg_cfg["force"]}"
interactive="${cmdarg_cfg["interactive"]}"
old="${argv[0]}"
new="${argv[1]}"

sudo mkdir -p "$(dirname "${new}")" 2>/dev/null
cmdArray=(sudo mv)

if [[ "${force}" == "true" ]]; then
  cmdArray+=(-f)
elif [[ "${interactive}" == "true" ]]; then
  cmdArray+=(-i)
fi

cmdArray+=("${old}" "${new}")

"${cmdArray[@]}"
