#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#
#  ████▄██▄  ██▄  ▄██  ██▄███▄
#  ██ ██ ██   ██  ██   ██▀  ▀██
#  ██ ██ ██   ▀█▄▄█▀   ██    ██
#  ██ ██ ██    ████    ███▄▄██▀
#  ▀▀ ▀▀ ▀▀     ▀▀     ██ ▀▀▀
#                      ██
#
# --- DESCRIPTION --- #
# Moves a file to a new location, creating the target directory if necessary
# --- DEPENDENCIES --- #
# - mkdir
# - mv
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
sudo mkdir -p "$(dirname "$2")" 2>/dev/null
sudo mv -i "$1" "$2"
