#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#
#  ████▄██▄  ██▄  ▄██  ██▄███▄
#  ██ ██ ██   ██  ██   ██▀  ▀██
#  ██ ██ ██   ▀█▄▄█▀   ██    ██
#  ██ ██ ██    ████    ███▄▄██▀
#  ▀▀ ▀▀ ▀▀     ▀▀     ██ ▀▀▀
#                      ██
#
# --- DESCRIPTION --- #
# Moves a file to a new location, creating the target directory if necessary
# --- DEPENDENCIES --- #
# - mkdir
# - mv
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "f" "force" "Do not prompt before overwriting"
cmdarg "i" "interactive" "Prompt before overwrite"

cmdarg_parse "$@"

force="${cmdarg_cfg["force"]}"
interactive="${cmdarg_cfg["interactive"]}"
old="${cmdarg_argv[0]}"
new="${cmdarg_argv[1]}"

sudo mkdir -p "$(dirname "${new}")" 2>/dev/null
cmdArray=(sudo mv)

if [[ "${force}" == "true" ]]; then
  cmdArray+=(-f "${old}" "${new}")
elif [[ "${interactive}" == "true" ]]; then
  cmdArray+=(-f "${old}" "${new}")
fi

# log-error "${cmdArray[@]}"
"${cmdArray[@]}"
