#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#
#
#  ██▄████▄
#  ██▀   ██
#  ██    ██
#  ██    ██
#  ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Runs a single command in nu shell
# --- DEPENDENCIES --- #
# - nu (nushell)
# - gum
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #

if ((argc == 0)); then
  command="$(gum write --placeholder="Enter a command...")"
else
  command="${argv[*]}"
fi

nu --config "${NU_CONFIG}" -c "${command}"
