#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#
#  ██▄████▄
#  ██▀   ██
#  ██    ██
#  ██    ██
#  ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
#
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #

if [[ $# -lt 1 ]]; then
  command=$(gum input --placeholder="Enter a command...")
else
  command="$*"
fi

nu --config "${NU_CONFIG}" -c "${command}"
