#!/usr/bin/env bash

INTERFACE="$(net-interface)"

DOWN_OLD="$(cat /sys/class/net/"${INTERFACE}"/statistics/rx_bytes)"
UP_OLD="$(cat /sys/class/net/"${INTERFACE}"/statistics/tx_bytes)"

while true; do
  sleep 1

  DOWN_NEW="$(cat /sys/class/net/"${INTERFACE}"/statistics/rx_bytes)"
  UP_NEW="$(cat /sys/class/net/"${INTERFACE}"/statistics/tx_bytes)"

  DOWN_DIFF=$((DOWN_NEW - DOWN_OLD))
  UP_DIFF=$((UP_NEW - UP_OLD))

  DOWN_SPEED=$((DOWN_DIFF * 8 / 1024)) # Kbps
  UP_SPEED=$((UP_DIFF * 8 / 1024))     # Kbps

  DOWN_OLD=${DOWN_NEW}
  UP_OLD=${UP_NEW}

  printf " %d Kbps  %d Kbps\n" "${DOWN_SPEED}" "${UP_SPEED}"
done
