#!/usr/bin/env bash

interface="$(ip route get 1.1.1.1 2>/dev/null | awk '{print $5;exit}')"

if [[ -n "${interface}" ]]; then
  echo "${interface}"
else
  interface="$(ip route get 8.8.8.8 2>/dev/null | awk '{print $5;exit}')"
  if [[ -n "${interface}" ]]; then
    echo "${interface}"
  else
    echo ""
  fi
fi
