#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                                                        ▄▄
#                        ██                                                              ██
#  ██▄████▄   ▄████▄   ███████             ▄▄█████▄  ██▄███▄    ▄████▄    ▄████▄    ▄███▄██
#  ██▀   ██  ██▄▄▄▄██    ██                ██▄▄▄▄ ▀  ██▀  ▀██  ██▄▄▄▄██  ██▄▄▄▄██  ██▀  ▀██
#  ██    ██  ██▀▀▀▀▀▀    ██       █████     ▀▀▀▀██▄  ██    ██  ██▀▀▀▀▀▀  ██▀▀▀▀▀▀  ██    ██
#  ██    ██  ▀██▄▄▄▄█    ██▄▄▄             █▄▄▄▄▄██  ███▄▄██▀  ▀██▄▄▄▄█  ▀██▄▄▄▄█  ▀██▄▄███
#  ▀▀    ▀▀    ▀▀▀▀▀      ▀▀▀▀              ▀▀▀▀▀▀   ██ ▀▀▀      ▀▀▀▀▀     ▀▀▀▀▀     ▀▀▀ ▀▀
#                                                    ██
#
# --- DESCRIPTION --- #
# Monitors and displays the network download and upload speeds in Kbps for the active network interface
# --- DEPENDENCIES --- #
# - cat
# - awk
# - printf
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
interface="$(net-interface)"

downOld="$(cat /sys/class/net/"${interface}"/statistics/rx_bytes)"
upOld="$(cat /sys/class/net/"${interface}"/statistics/tx_bytes)"

printf '\n'
while true; do
  downNew="$(cat /sys/class/net/"${interface}"/statistics/rx_bytes)"
  upNew="$(cat /sys/class/net/"${interface}"/statistics/tx_bytes)"

  downDiff=$((downNew - downOld))
  upDiff=$((upNew - upOld))

  downSpeed=$((downDiff * 8 / 1024)) # Kbps
  upSpeed=$((upDiff * 8 / 1024))     # Kbps

  downOld="${downNew}"
  upOld="${upNew}"

  eraseLine
  printf " %d Kbps  %d Kbps\n" "${downSpeed}" "${upSpeed}"
  sleep 1
done
