#!/usr/bin/env bash

interface="$(net-interface)"

downOld="$(cat /sys/class/net/"${interface}"/statistics/rx_bytes)"
upOld="$(cat /sys/class/net/"${interface}"/statistics/tx_bytes)"

while true; do
  sleep 1

  downNew="$(cat /sys/class/net/"${interface}"/statistics/rx_bytes)"
  upNew="$(cat /sys/class/net/"${interface}"/statistics/tx_bytes)"

  downDiff=$((downNew - downOld))
  upDiff=$((upNew - upOld))

  downSpeed=$((downDiff * 8 / 1024)) # Kbps
  upSpeed=$((upDiff * 8 / 1024))     # Kbps

  downOld=${downNew}
  upOld=${upNew}

  printf " %d Kbps  %d Kbps\n" "${downSpeed}" "${upSpeed}"
done
