#!/usr/bin/env bash

set -euo pipefail

trap 'exit 1' SIGUSR1

backup=0

while getopts "b" opt; do
  case ${opt} in
  b) backup=1 ;;
  ? | *) log-error "Invalid option: -${OPTARG}" ;;
  esac
done
shift $((OPTIND - 1))

file="$1"
tmpfile="$(mktemp)"
trap 'rm -f $tmpfile' EXIT

if [[ -z ${file} || ${file} == "-" ]]; then
  # Read from stdin
  awk '!a[$0]++' | tee "${tmpfile}" >/dev/null
  cat "${tmpfile}"
else
  # Read from file
  if [[ -f ${file} ]]; then
    if [[ ${backup} -eq 1 ]]; then
      cp "${file}" "${file}.bak"
      log-info "Backup created as ${file}.bak"
    fi
    awk '!a[$0]++' "${file}" >"${tmpfile}"
    mv "${tmpfile}" "${file}"
    log-info "Duplicates removed from '${file}'!"
  else
    log-error "'${file}' was not found!"
  fi
fi
