#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                      ▄▄
#                                      ██
#  ██▄████▄   ▄████▄              ▄███▄██  ██    ██  ██▄███▄   ▄▄█████▄
#  ██▀   ██  ██▀  ▀██            ██▀  ▀██  ██    ██  ██▀  ▀██  ██▄▄▄▄ ▀
#  ██    ██  ██    ██   █████    ██    ██  ██    ██  ██    ██   ▀▀▀▀██▄
#  ██    ██  ▀██▄▄██▀            ▀██▄▄███  ██▄▄▄███  ███▄▄██▀  █▄▄▄▄▄██
#  ▀▀    ▀▀    ▀▀▀▀                ▀▀▀ ▀▀   ▀▀▀▀ ▀▀  ██ ▀▀▀     ▀▀▀▀▀▀
#                                                    ██
#
# --- DESCRIPTION --- #
# Removes duplicate lines from a file or stdin, with options for backup, output as array, and quiet mode
# --- DEPENDENCIES --- #
# - tr
# - awk
# - paste
# - mktemp
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
# ---  Main script logic --- #

cmdarg "b" "backup" "Creates a backup .bak file of the original file"
cmdarg "f" "force" "Overwrite the original file without cofirmation"
cmdarg "a" "array" "Returns the output as a bash compatible array"
cmdarg "q" "quiet" "Runs quietly without output on success"

cmdarg_parse "$@"

useBackup=${cmdarg_cfg['backup']}
force=${cmdarg_cfg['force']}
useArray=${cmdarg_cfg['array']}
quiet=${cmdarg_cfg['quiet']}

# Function to process input and remove duplicates
remove_duplicates() {
  if [[ ${useArray} == true ]]; then
    tr ' ' '\n' | awk '!a[$0]++' | paste -sd " "
  else
    awk '!a[$0]++'
  fi
}

file=${argv[0]}

# Check if input is from a file or stdin
if [[ -z ${file} || ${file} == "-" ]]; then
  remove_duplicates
else
  tmpfile="$(mktemp)"
  trap 'rm -f $tmpfile' EXIT

  # Read from file
  if [[ -f ${file} ]]; then
    if [[ ${useBackup} == true ]]; then
      cp "${file}" "${file}.bak"
      [[ ${quiet} == true ]] || log-info "Backup created as ${file}.bak"
    fi

    remove_duplicates <"${file}" >"${tmpfile}"

    # override the input file
    if [[ ${force} == true ]]; then
      mv "${tmpfile}" "${file}"
    else
      mv -i "${tmpfile}" "${file}"
    fi

    [[ ${quiet} == true ]] || log-info "Duplicates removed from '${file}'!"
  else
    log-error "File: '${file}' was not found!"
  fi
fi
