#!/usr/bin/env bash

# shellcheck disable=SC1091
source logs.sh

file="$1"

if [[ -f $file ]]; then
  tmpfile="$(mktemp)"
  awk '!x[$0]++' "$file" > "$tmpfile"
  cat "$tmpfile" > "$file"
  rm -f "$tmpfile"
  log_info "Duplicates removed!"
else
  log_error "$file was not found!"
fi

