#!/usr/bin/env bash

file="$1"

if [[ -f $file ]]; then
  tmpfile="$(mktemp)"
  awk '!x[$0]++' "$file" >"$tmpfile"
  cat "$tmpfile" >"$file"
  rm -f "$tmpfile"
  log-info "Duplicates removed!"
else
  log-error "$file was not found!"
fi
