#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#
#  ██▄████▄   ▄████▄  ██      ██
#  ██▀   ██  ██▀  ▀██ ▀█  ██  █▀
#  ██    ██  ██    ██  ██▄██▄██
#  ██    ██  ▀██▄▄██▀  ▀██  ██▀
#  ▀▀    ▀▀    ▀▀▀▀     ▀▀  ▀▀
#
#
# --- DESCRIPTION --- #
# Prints the current date and time
# --- DEPENDENCIES --- #
# - date
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

eval "$(include "check-deps")"
checkDeps "$0"
# ---  Main script logic --- #
date +"%Y-%m-%d@%I:%M%p"
