#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#
#
#  ██▄████▄   ▄████▄  ██      ██
#  ██▀   ██  ██▀  ▀██ ▀█  ██  █▀
#  ██    ██  ██    ██  ██▄██▄██
#  ██    ██  ▀██▄▄██▀  ▀██  ██▀
#  ▀▀    ▀▀    ▀▀▀▀     ▀▀  ▀▀
#
#
# --- DESCRIPTION --- #
# Prints the current date and time
# --- DEPENDENCIES --- #
# - date
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
date +"%Y-%m-%d@%I:%M%p"
