#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#
#   ▄████▄    ▄█████▄   ██▄████
#  ██▀  ▀██  ██▀    ▀   ██▀
#  ██    ██  ██         ██
#  ▀██▄▄██▀  ▀██▄▄▄▄█   ██
#    ▀▀▀▀      ▀▀▀▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Extract text from an image using Tesseract
# --- DEPENDENCIES --- #
# - tesseract
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

source cmdarg.sh

# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc $0)"

cmdarg "s" "save" "Save the result to a file"

cmdarg_parse "$@"

saveToFile=${cmdarg_cfg['save']}
image=${cmdarg_argv[0]}

[[ -f "${image}" ]] || log-error "file '${image}' was not found!"

if [[ ${saveToFile} == true ]]; then

  imgNameWithoutExt="$(strip-ext ${image} png jpg jpeg webp svg gif)"

  tesseract "${image}" "${imgNameWithoutExt}" 2 &>/dev/null ||
    log-error "Tesseract failed on '${image}'."

  log-success "Result saved as '${imgNameWithoutExt}.txt'"
else
  outputFile="$(mktemp -t ocr-XXXXX)"
  trap 'rm -f $outputFile' EXIT

  if ! tesseract "${image}" "${outputFile}" 2 &>/dev/null; then
    log-error "Tesseract failed on '${image}'."
  fi

  output=$(cat "${outputFile}.txt")
  [[ -z ${output} ]] && log-warning "No readable text found in image '${image}'"

  cat "${outputFile}.txt"
fi
