#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#                                                   
#                                                   
#                                                   
#   ▄████▄    ▄█████▄   ██▄████   ▄█████▄  ██▄███▄  
#  ██▀  ▀██  ██▀    ▀   ██▀      ██▀    ▀  ██▀  ▀██ 
#  ██    ██  ██         ██       ██        ██    ██ 
#  ▀██▄▄██▀  ▀██▄▄▄▄█   ██       ▀██▄▄▄▄█  ███▄▄██▀ 
#    ▀▀▀▀      ▀▀▀▀▀    ▀▀         ▀▀▀▀▀   ██ ▀▀▀   
#                                          ██       
#                                                   
# --- DESCRIPTION --- #
# OCR an image and copy the result to clipboard
# --- DEPENDENCIES --- #
# - tesseract
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

# ---  Main script logic --- #
file="$1"

[[ -f "${file}" ]] || log-error "file '${file}' was not found!"

text=$(ocr ${file})

if [[ -z "${text}" ]]; then
  log-warning "Tesseract produced no output for '${file}'."
else
  echo "${text}" | clipcopy || log-error "Copy to clipboard failed."
  log-success "Text from '${file}' copied to clipboard."
fi
