#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                          ▄▄
#                                          ██                    ██
#   ▄████▄    ▄█████▄   ██▄████  ▄▄█████▄  ██▄████▄   ▄████▄   ███████
#  ██▀  ▀██  ██▀    ▀   ██▀      ██▄▄▄▄ ▀  ██▀   ██  ██▀  ▀██    ██
#  ██    ██  ██         ██        ▀▀▀▀██▄  ██    ██  ██    ██    ██
#  ▀██▄▄██▀  ▀██▄▄▄▄█   ██       █▄▄▄▄▄██  ██    ██  ▀██▄▄██▀    ██▄▄▄
#    ▀▀▀▀      ▀▀▀▀▀    ▀▀        ▀▀▀▀▀▀   ▀▀    ▀▀    ▀▀▀▀       ▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Screen OCR: select a region, copy extracted text to clipboard.
# Related script: ocr, ocrcp
# --- DEPENDENCIES --- #
# - tesseract
# - flameshot
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/cmdarg.sh")"
source "$(include "lib/helpers.sh")"
source "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #

flameshot gui -r 2>/dev/null | tesseract stdin stdout 2>/dev/null | clipcopy

notify-send -a "${BASH_SOURCE[0]##*\/}" "Done!" &
