#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                     ▄▄▄▄
#            ██                    ██▀▀▀               ██
#  ██▄███▄   ██▄████▄  ██▄███▄   ███████   ████▄██▄  ███████
#  ██▀  ▀██  ██▀   ██  ██▀  ▀██    ██      ██ ██ ██    ██
#  ██    ██  ██    ██  ██    ██    ██      ██ ██ ██    ██
#  ███▄▄██▀  ██    ██  ███▄▄██▀    ██      ██ ██ ██    ██▄▄▄
#  ██ ▀▀▀    ▀▀    ▀▀  ██ ▀▀▀      ▀▀      ▀▀ ▀▀ ▀▀     ▀▀▀▀
#  ██                  ██
#
# --- DESCRIPTION --- #
# Formats PHP files using phpcbf, auto-discovers .php/.inc files
# --- DEPENDENCIES --- #
# - phpcbf (php-codesniffer)
# - fd | fdfind (fd-find)
# --- END SIGNATURE --- #

trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "lib/helpers.sh")"
eval "$(include "check-deps")"

checkDeps "$0"

cmdarg_info "header" "$(get-desc "$0")"
cmdarg "q" "quiet" "Supress output"
cmdarg "b" "backup" "Create backup with suffix"
cmdarg_parse "$@"
# ---  Main script logic --- #

isQuiet="${cmdarg_cfg['quiet']}"
backup="${cmdarg_cfg['backup']}"

declare -a files
target="${argv[0]}"

if [[ -d "${target}" ]]; then
  mapfile -t files < <(fd.sh . -I -e php -e inc "${target}")
else
  for file in "${argv[@]}"; do
    [[ -s "${file}" && "${file##*.}" =~ ^(php|inc)$ ]] && files+=("${file}")
  done
fi

filesCount=${#files[@]}

if ((filesCount == 0)); then
  phpcbf '--stdin-path=file.php' -n -
  exit 0
  log-error "No valid php files were passed"
fi

cmd=(
  phpcbf
  -n
  -p
  --parallel=$(($(nproc) / 2 + 1))
)

"${backup}" && cmd+=("--suffix=.bak")

cmd+=("${files[@]}")

"${cmd[@]}"

"${isQuiet}" || log-success "Formatted ${filesCount} files"
