#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                     ▄▄▄▄
#            ██                    ██▀▀▀               ██
#  ██▄███▄   ██▄████▄  ██▄███▄   ███████   ████▄██▄  ███████
#  ██▀  ▀██  ██▀   ██  ██▀  ▀██    ██      ██ ██ ██    ██
#  ██    ██  ██    ██  ██    ██    ██      ██ ██ ██    ██
#  ███▄▄██▀  ██    ██  ███▄▄██▀    ██      ██ ██ ██    ██▄▄▄
#  ██ ▀▀▀    ▀▀    ▀▀  ██ ▀▀▀      ▀▀      ▀▀ ▀▀ ▀▀     ▀▀▀▀
#  ██                  ██
#
# --- DESCRIPTION --- #
# Formats PHP files using phpcbf; accepts files, directories, or reads from stdin
# --- DEPENDENCIES --- #
# - phpcbf (php-codesniffer)
# --- END SIGNATURE --- #

trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "lib/helpers.sh")"
eval "$(include "check-deps")"

checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "q" "quiet" "Supress output"
cmdarg "b" "backup" "Create backup with suffix"
cmdarg_parse "$@"
# ---  Main script logic --- #

isQuiet="${cmdarg_cfg['quiet']}"
backup="${cmdarg_cfg['backup']}"

cmd=(phpcbf -n -p --parallel=$(($(nproc) / 2 + 1)))

"${isQuiet}" && cmd+=(-q)
"${backup}" && cmd+=("--suffix=.bak")

if ((argc == 0)); then
  if [[ ! -t 0 ]]; then
    cmd+=(--stdin-path=file.php -)
    "${cmd[@]}"
    exit 0
  fi
  cmd+=(.)
else
  cmd+=("${argv[@]}")
fi

"${cmd[@]}"
