#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                    ▄▄▄▄
#                                                    ▀▀██
#  ██▄███▄   ██▄████▄  ██▄███▄   ████▄██▄              ██      ▄▄█████▄
#  ██▀  ▀██  ██▀   ██  ██▀  ▀██  ██ ██ ██              ██      ██▄▄▄▄ ▀
#  ██    ██  ██    ██  ██    ██  ██ ██ ██   █████      ██       ▀▀▀▀██▄
#  ███▄▄██▀  ██    ██  ███▄▄██▀  ██ ██ ██              ██▄▄▄   █▄▄▄▄▄██
#  ██ ▀▀▀    ▀▀    ▀▀  ██ ▀▀▀    ▀▀ ▀▀ ▀▀               ▀▀▀▀    ▀▀▀▀▀▀
#  ██                  ██
#
# --- DESCRIPTION --- #
# List globally installed pnpm packages
# --- DEPENDENCIES --- #
# - pnpm
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
pnpm ls -g --no-color --json | jq -r '.[0].dependencies | keys | sort | .[]'
