#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                         ██
#                         ▀▀                 ██
#  ██▄███▄    ██▄████   ████     ██▄████▄  ███████              ▄█████▄   ██▄████   ▄███▄██  ▄▄█████▄
#  ██▀  ▀██   ██▀         ██     ██▀   ██    ██                 ▀ ▄▄▄██   ██▀      ██▀  ▀██  ██▄▄▄▄ ▀
#  ██    ██   ██          ██     ██    ██    ██       █████    ▄██▀▀▀██   ██       ██    ██   ▀▀▀▀██▄
#  ███▄▄██▀   ██       ▄▄▄██▄▄▄  ██    ██    ██▄▄▄             ██▄▄▄███   ██       ▀██▄▄███  █▄▄▄▄▄██
#  ██ ▀▀▀     ▀▀       ▀▀▀▀▀▀▀▀  ▀▀    ▀▀     ▀▀▀▀              ▀▀▀▀ ▀▀   ▀▀        ▄▀▀▀ ██   ▀▀▀▀▀▀
#  ██                                                                               ▀████▀▀
#
# --- DESCRIPTION --- #
# Spits out all of its arguments
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/helpers.sh")"
# ---  Main script logic --- #
if [[ $1 != '-q' ]]; then
  log-debug "$# args"
else
  shift
fi

(($#)) && printf '[%s]\n' "$@"
