#!/usr/bin/env bash

# shellcheck disable=SC1091
source logs.sh

cmd="$1"

# Infinite loop: repeat the command until it exits successfully
while true; do
    
    if $cmd; then
        break
    fi
    
    log-info "Retrying in 5s..."
    sleep 5s
    clear
    echo "$cmd"
done
