#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                                           ██
#                                                      ██                   ▀▀       ██
#   ██▄████   ▄████▄   ██▄███▄    ▄████▄    ▄█████▄  ███████              ████     ███████
#   ██▀      ██▄▄▄▄██  ██▀  ▀██  ██▄▄▄▄██   ▀ ▄▄▄██    ██                   ██       ██
#   ██       ██▀▀▀▀▀▀  ██    ██  ██▀▀▀▀▀▀  ▄██▀▀▀██    ██       █████       ██       ██
#   ██       ▀██▄▄▄▄█  ███▄▄██▀  ▀██▄▄▄▄█  ██▄▄▄███    ██▄▄▄             ▄▄▄██▄▄▄    ██▄▄▄
#   ▀▀         ▀▀▀▀▀   ██ ▀▀▀      ▀▀▀▀▀    ▀▀▀▀ ▀▀     ▀▀▀▀             ▀▀▀▀▀▀▀▀     ▀▀▀▀
#                      ██
#
# --- DESCRIPTION --- #
# Repeat a command until it succeeds
# --- DEPENDENCIES --- #
# - gum
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/helpers.sh")"
source "$(include "lib/cmdarg.sh")"
source "$(include "check-deps")"

checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "n" "notify" "Play the terminal's bell when the command finishes"
cmdarg "p" "preserve" "Preserve output between retries (don't clear the screen)"
cmdarg "d?" "delay" "Delay in seconds between retries" "5"
cmdarg "t?" "tries" "If command didn't complete after n tries, exit" ""

cmdarg_parse "$@"
# ---  Main script logic --- #

preserve="${cmdarg_cfg['preserve']}"
notify="${cmdarg_cfg['notify']}"
delay="${cmdarg_cfg['delay']}"
tries="${cmdarg_cfg['tries']}"
cmd="${argv[*]}"
"${notify}" && trap 'printf "\a"' EXIT

# validate the delay if defined
if [[ -n "${delay}" ]]; then
  isPositive "${delay}" || log-error "Delay must be a positive number"
fi

# validate the tries count if defined
if [[ -n "${tries}" ]]; then
  isPositiveInt "${tries}" || log-error "Tries must be a positive number"
fi

if [[ -z "${cmd}" ]]; then
  cmd="$(gum write --placeholder "enter a command to repeat...")"
fi

# Check if the command is empty
[[ -z "${cmd}" ]] && log-error "No command entered."

counter=1
# Infinite loop: repeat until success or interruption
while true; do
  if bash -c "${cmd}"; then
    if ((counter > 1)); then
      printf '\n'
      log-success "Done after ${counter} retries 🚀!"
    fi
    break
  fi

  if [[ "${counter}" == "${tries}" ]]; then
    terminate "Program terminated after ${counter} retries"
  fi

  # Run gum spin, and check its exit status
  if ! gum spin \
    --title "Retrying '${cmd}' in ${delay}s..." \
    -- sleep "${delay}"; then
    # If gum spin fails (e.g., due to Ctrl+C), exit
    printf '\n'
    if ((counter > 1)); then
      terminate "Program terminated after ${counter} retries"
    else
      terminate
    fi
  fi

  "${preserve}" || clear
  ((counter++))
done
