#!/usr/bin/env bash

trap 'exit 1' SIGUSR1

cmd="$1"
counter=1

if [[ $# -eq 0 ]]; then
  cmd=$(gum write --placeholder "enter a command to repeat...")
  # Evaluate the command to parse variables
  cmd=$(eval echo "${cmd}")
fi

# Check if the command is empty
[[ -z "${cmd}" ]] && log-error "No command entered."

# Infinite loop: repeat until success or interruption
while true; do
  if eval "${cmd}"; then
    [[ ! ${counter} -eq 1 ]] && log-success "\nDone after ${counter} retries 🚀!"
    break
  fi

  # Run gum spin, and check its exit status
  if ! gum spin --spinner dot \
    --title "Retrying '${cmd}' in 5s..." \
    --title.foreground="${U_GREEN}" \
    --spinner.foreground="${U_GREEN}" \
    -- sleep 5; then
    # If gum spin fails (e.g., due to Ctrl+C), exit
    exit 0
  fi

  clear
  counter=$((counter + 1))
done
