#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                ▄▄           ██               ▄▄
#                                ██           ▀▀               ██
#   ██▄████  ████▄██▄ ██      ██ ██▄████▄   ████      ▄█████▄  ██▄████▄
#   ██▀      ██ ██ ██ ▀█  ██  █▀ ██▀   ██     ██     ██▀    ▀  ██▀   ██
#   ██       ██ ██ ██  ██▄██▄██  ██    ██     ██     ██        ██    ██
#   ██       ██ ██ ██  ▀██  ██▀  ██    ██  ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ██    ██
#   ▀▀       ▀▀ ▀▀ ▀▀   ▀▀  ▀▀   ▀▀    ▀▀  ▀▀▀▀▀▀▀▀    ▀▀▀▀▀   ▀▀    ▀▀
#
#
# --- DESCRIPTION --- #
# Deletes the source of a script, if it exists
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg "force" "f" "Deletes without confirmation"
cmdarg_parse "$@"
# ---  Main script logic --- #
force="${cmdarg_cfg['force']}"
file="${argv[0]}"

[[ -z "${file}" ]] && log-error "No valid input was given!"

if path=$(command -v "${file}" 2>/dev/null); then
  if "${force}"; then
    sudo rm -fv "${path}"
  else
    sudo rm -i "${path}"
  fi
else
  log-error "Script ${file} doesn't exist!"
fi
