#!/usr/bin/env bash

dir="$(dirname $0)/python"
venv="${dir}/.venv/bin/activate"
file="${dir}/$(basename $1).py"

# remove the script name from arguments and pass them to the target script
shift

withVenv() {
  source "${venv}" || exit

  python3 "${file}" "$@" || {
    deactivate && exit
  }

  deactivate
}

if [[ -f "${venv}" ]]; then
  withVenv "$@"
else
  python3 "${file}" "$@" && exit 0
fi
