#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#
#
#   ██▄████  ██    ██  ██▄████▄  ██▄███▄   ▀██  ███
#   ██▀      ██    ██  ██▀   ██  ██▀  ▀██   ██▄ ██
#   ██       ██    ██  ██    ██  ██    ██    ████▀
#   ██       ██▄▄▄███  ██    ██  ███▄▄██▀     ███
#   ▀▀        ▀▀▀▀ ▀▀  ▀▀    ▀▀  ██ ▀▀▀       ██
#                                ██         ███
#
# --- DESCRIPTION --- #
# Run a Python script from $SCRIPTS_DIR/python with optional venv
# --- DEPENDENCIES --- #
# - python3
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

check-deps "$0"
# ---  Main script logic --- #
dir="${SCRIPTS_DIR}/python"
venv="${dir}/.venv/bin/activate"
file="${dir}/$(basename $1).py"

# remove the script name from arguments and pass them to the target script
shift

withVenv() {
  source "${venv}" || exit

  python3 "${file}" "$@"
  deactivate && exit
}

if [[ -f "${venv}" ]]; then
  withVenv "$@"
else
  python3 "${file}" "$@" && exit 0
fi
