#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                          ▄▄                            ▄▄
#                                  ██      ██                            ██
#   ██▄████  ██    ██  ▄▄█████▄  ███████   ██▄███▄    ▄████▄    ▄████▄   ██ ▄██▀
#   ██▀      ██    ██  ██▄▄▄▄ ▀    ██      ██▀  ▀██  ██▀  ▀██  ██▀  ▀██  ██▄██
#   ██       ██    ██   ▀▀▀▀██▄    ██      ██    ██  ██    ██  ██    ██  ██▀██▄
#   ██       ██▄▄▄███  █▄▄▄▄▄██    ██▄▄▄   ███▄▄██▀  ▀██▄▄██▀  ▀██▄▄██▀  ██  ▀█▄
#   ▀▀        ▀▀▀▀ ▀▀   ▀▀▀▀▀▀      ▀▀▀▀   ▀▀ ▀▀▀      ▀▀▀▀      ▀▀▀▀    ▀▀   ▀▀▀
#
#
# --- DESCRIPTION --- #
# Launch the rust book using vite
# --- DEPENDENCIES --- #
# - vite
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
cd "${HOME}/.local/share/rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/book" || log-error "Cannot find the book"

vite --config "${HOME}/.config/vite/vite.config.js" --port 9001 --open
