#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                      ▄▄▄▄
#                      ▀▀██
#  ▄▄█████▄   ▄████▄     ██       ▄█████▄  ██▄███▄
#  ██▄▄▄▄ ▀  ██▄▄▄▄██    ██      ██▀    ▀  ██▀  ▀██
#   ▀▀▀▀██▄  ██▀▀▀▀▀▀    ██      ██        ██    ██
#  █▄▄▄▄▄██  ▀██▄▄▄▄█    ██▄▄▄   ▀██▄▄▄▄█  ███▄▄██▀
#   ▀▀▀▀▀▀     ▀▀▀▀▀      ▀▀▀▀     ▀▀▀▀▀   ██ ▀▀▀
#                                          ██
#
# --- DESCRIPTION --- #
# Copy selected text using xsel
# --- DEPENDENCIES --- #
# - xsel
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/cmdarg.sh")"
source "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
xsel | clipcopy
