#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                      ▄▄▄▄
#                      ▀▀██
#  ▄▄█████▄   ▄████▄     ██       ▄█████▄  ██▄███▄
#  ██▄▄▄▄ ▀  ██▄▄▄▄██    ██      ██▀    ▀  ██▀  ▀██
#   ▀▀▀▀██▄  ██▀▀▀▀▀▀    ██      ██        ██    ██
#  █▄▄▄▄▄██  ▀██▄▄▄▄█    ██▄▄▄   ▀██▄▄▄▄█  ███▄▄██▀
#   ▀▀▀▀▀▀     ▀▀▀▀▀      ▀▀▀▀     ▀▀▀▀▀   ██ ▀▀▀
#                                          ██
#
# --- DESCRIPTION --- #
# Copy selected text using xsel
# --- DEPENDENCIES --- #
# - xsel
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

check-deps "$0"
# ---  Main script logic --- #
xsel | clipcopy
