#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄                    ▄▄▄
#            ██                   █▀██
#  ▄▄█████▄  ██▄████▄   ▄█████▄     ██
#  ██▄▄▄▄ ▀  ██▀   ██   ▀ ▄▄▄██     ██
#   ▀▀▀▀██▄  ██    ██  ▄██▀▀▀██     ██
#  █▄▄▄▄▄██  ██    ██  ██▄▄▄███  ▄▄▄██▄▄▄
#   ▀▀▀▀▀▀   ▀▀    ▀▀   ▀▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
# Prints a SHA-1 hash
# --- DEPENDENCIES --- #
# - sha1sum
# - printf
# - tr
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
params=$(echo "$*" | tr -d "\n" | trim)
printf "%s" "${params}" | sha1sum | awk '{print $1}'
