#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                   ██
#              ██                   ▀▀                                               ██
#  ▄▄█████▄  ███████    ██▄████   ████     ██▄███▄              ▄████▄   ▀██  ██▀  ███████
#  ██▄▄▄▄ ▀    ██       ██▀         ██     ██▀  ▀██            ██▄▄▄▄██    ████      ██
#   ▀▀▀▀██▄    ██       ██          ██     ██    ██   █████    ██▀▀▀▀▀▀    ▄██▄      ██
#  █▄▄▄▄▄██    ██▄▄▄    ██       ▄▄▄██▄▄▄  ███▄▄██▀            ▀██▄▄▄▄█   ▄█▀▀█▄     ██▄▄▄
#   ▀▀▀▀▀▀      ▀▀▀▀    ▀▀       ▀▀▀▀▀▀▀▀  ██ ▀▀▀                ▀▀▀▀▀   ▀▀▀  ▀▀▀     ▀▀▀▀
#                                          ██
#
# --- DESCRIPTION --- #
# Remove extension(s) from a file name
# --- DEPENDENCIES --- #
# - basename
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
file="$1"
shift

if [[ $# == 0 ]]; then
  basename "${file}"
  exit 0
else
  filename="${file}"
  for ext in "$@"; do
    filename=$(basename -s ".${ext}" "${filename}")
    filename=$(echo "${filename}" | replace ".${ext}" "")
  done
fi

echo "${filename}"
