#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                                                          ▄▄     ██
#    ██                                                    ██     ▀▀       ██
#  ███████    ▄████▄   ████▄██▄  ██▄███▄    ▄████▄    ▄███▄██   ████     ███████
#    ██      ██▄▄▄▄██  ██ ██ ██  ██▀  ▀██  ██▄▄▄▄██  ██▀  ▀██     ██       ██
#    ██      ██▀▀▀▀▀▀  ██ ██ ██  ██    ██  ██▀▀▀▀▀▀  ██    ██     ██       ██
#    ██▄▄▄   ▀██▄▄▄▄█  ██ ██ ██  ███▄▄██▀  ▀██▄▄▄▄█  ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄
#     ▀▀▀▀     ▀▀▀▀▀   ▀▀ ▀▀ ▀▀  ██ ▀▀▀      ▀▀▀▀▀     ▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀
#                                ██
#
# --- DESCRIPTION --- #
# Creates a temporary file to edit with the given extesnsion
# --- DEPENDENCIES --- #
#
# --- END SIGNATURE --- #

set -eo pipefail

trap 'exit 1' SIGUSR1

source cmdarg.sh

# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "p" "--preserve" "Keep the file after the editing is done, the default is deleting it."

cmdarg_parse "$@"

# Store option values
preserve=${cmdarg_cfg['preserve']}

extension=${cmdarg_argv[0]:-md}

EDITOR=${EDITOR:-nano}

file=$(mktemp -t "XXXXXX.${extension}")

[[ ${preserve} == true ]] || trap 'rm -f $file' EXIT

${EDITOR} "${file}"
