#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                                          ▄▄     ██
#    ██                                                    ██     ▀▀       ██
#  ███████    ▄████▄   ████▄██▄  ██▄███▄    ▄████▄    ▄███▄██   ████     ███████
#    ██      ██▄▄▄▄██  ██ ██ ██  ██▀  ▀██  ██▄▄▄▄██  ██▀  ▀██     ██       ██
#    ██      ██▀▀▀▀▀▀  ██ ██ ██  ██    ██  ██▀▀▀▀▀▀  ██    ██     ██       ██
#    ██▄▄▄   ▀██▄▄▄▄█  ██ ██ ██  ███▄▄██▀  ▀██▄▄▄▄█  ▀██▄▄███  ▄▄▄██▄▄▄    ██▄▄▄
#     ▀▀▀▀     ▀▀▀▀▀   ▀▀ ▀▀ ▀▀  ██ ▀▀▀      ▀▀▀▀▀     ▀▀▀ ▀▀  ▀▀▀▀▀▀▀▀     ▀▀▀▀
#                                ██
#
# --- DESCRIPTION --- #
# Creates a temporary file to edit with the given extesnsion
# --- DEPENDENCIES --- #
# - nano
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg "p" "preserve" "Keep the file after the editing is done, the default is deleting it."
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #

# Store option values
preserve="${cmdarg_cfg['preserve']}"

extension="${argv[0]:-md}"

EDITOR="${EDITOR:-nano}"

file=$(mktemp -t "tempedit-XXXXX.${extension}")
if [[ ${preserve} == true ]]; then
  clipcopy "${file}"
  log-info "File name copied to clipboard!"
else
  trap 'rm -f $file' EXIT
fi

${EDITOR} "${file}"
