#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#                                          ▄▄▄▄                ▄▄   ▄▄▄  ▄▄▄▄▄▄
#    ██                                    ▀▀██                ██  ██▀   ██▀▀▀▀██
#  ███████    ▄████▄    ▄███▄██   ▄███▄██    ██       ▄████▄   ██▄██     ██    ██
#    ██      ██▀  ▀██  ██▀  ▀██  ██▀  ▀██    ██      ██▄▄▄▄██  █████     ███████
#    ██      ██    ██  ██    ██  ██    ██    ██      ██▀▀▀▀▀▀  ██  ██▄   ██    ██
#    ██▄▄▄   ▀██▄▄██▀  ▀██▄▄███  ▀██▄▄███    ██▄▄▄   ▀██▄▄▄▄█  ██   ██▄  ██▄▄▄▄██
#     ▀▀▀▀     ▀▀▀▀     ▄▀▀▀ ██   ▄▀▀▀ ██     ▀▀▀▀     ▀▀▀▀▀   ▀▀    ▀▀  ▀▀▀▀▀▀▀
#                       ▀████▀▀   ▀████▀▀
#
# --- DESCRIPTION --- #
# Toggle keyboard layout between us and eg
# --- DEPENDENCIES --- #
# - setxkbmap
# - notify-send (libnotify)
# --- END SIGNATURE --- #

set -o pipefail

trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
getCurrentLayout() {
  setxkbmap -query | grep layout | awk '{print $2}'
}

if [[ "$(getCurrentLayout)" == "eg" ]]; then
  setxkbmap -layout us && notify-send "changed layout to $(getCurrentLayout)"
else
  setxkbmap -layout eg && notify-send "changed layout to $(getCurrentLayout)"
fi
