#!/usr/bin/env bash

set -eo pipefail

trap 'exit 1' SIGUSR1

source cmdarg.sh

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
cmdarg_info "header" "$(get-desc "$0")"

cmdarg "b" "backup" "Creates a backup .bak file of the original file"

cmdarg_parse "$@"

useBackup=${cmdarg_cfg['backup']}
file=${cmdarg_argv[0]}

if [[ ${#cmdarg_argv[@]} -eq 0 || ${file} == "-" ]]; then
  str=$(cat)
  [[ -z ${str} ]] && printf '' && exit 0
  echo "${str}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
elif [[ -f ${file} ]]; then
  if [[ ${useBackup} == true ]]; then
    cp -i "${file}" "${file}.bak"
    sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -i "${file}"
    log-success "Trimmed whitespaces from '${file}'. Backup created at '${file}.bak'."
  else
    sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -i "${file}"
    log-success "Trimmed whitespaces from ${file}"
  fi
else
  str="$*"
  [[ -z ${str} ]] && printf '' && exit 0
  echo "${str}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
fi
