#!/usr/bin/env bash

set -euo pipefail

trap 'exit 1' SIGUSR1

# read from stdin
if [[ $# -eq 0 || $1 == "-" ]]; then
  str=$(cat)
else
  str="$*"
fi

[[ -z ${str} ]] && printf '' && exit 0

echo "${str}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
