#!/usr/bin/env bash

# --- SCRIPT SIGNATURE --- #
#
#                                ▄▄
#    ██                          ██
#  ███████   ██    ██   ▄█████▄  ██ ▄██▀    ██▄████            ▄▄█████▄  ▀██  ███  ██▄████▄   ▄█████▄
#    ██      ██    ██  ██▀    ▀  ██▄██      ██▀                ██▄▄▄▄ ▀   ██▄ ██   ██▀   ██  ██▀    ▀
#    ██      ██    ██  ██        ██▀██▄     ██        █████     ▀▀▀▀██▄    ████▀   ██    ██  ██
#    ██▄▄▄   ██▄▄▄███  ▀██▄▄▄▄█  ██  ▀█▄    ██                 █▄▄▄▄▄██     ███    ██    ██  ▀██▄▄▄▄█
#     ▀▀▀▀    ▀▀▀▀ ▀▀    ▀▀▀▀▀   ▀▀   ▀▀▀   ▀▀                  ▀▀▀▀▀▀      ██     ▀▀    ▀▀    ▀▀▀▀▀
#                                                                         ███
#
# --- DESCRIPTION --- #
# Sync all top-level Tuckr packages
# --- DEPENDENCIES --- #
# - tuckr
# - fd | fdfind (fd-find)
# - cut
# --- END SIGNATURE --- #

set -euo pipefail

trap 'exit 1' SIGUSR1

source check-deps
checkDeps "$0"
# ---  Main script logic --- #
path=${TUCKR_DIR:-${HOME}/.config/dotfiles/Configs}

cd "${path}" || log-error "Invalid tuckr directory: ${path}"

packages=($(fd . --type d -d 1 | cut -d '/' -f1))

count=0
for package in "${packages[@]}"; do
  tuckr add "${package}" || log-warning "Failed to sync package ${package}"
  count=$((count + 1))
done

log-success "Synced ${count} tuckr packages"
