#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#
#                                            ██
#  ██    ██  ██▄████▄  ▄▄█████▄   ▄████▄   ███████    ▄████▄   ██▄████▄  ██▄  ▄██
#  ██    ██  ██▀   ██  ██▄▄▄▄ ▀  ██▄▄▄▄██    ██      ██▄▄▄▄██  ██▀   ██   ██  ██
#  ██    ██  ██    ██   ▀▀▀▀██▄  ██▀▀▀▀▀▀    ██      ██▀▀▀▀▀▀  ██    ██   ▀█▄▄█▀
#  ██▄▄▄███  ██    ██  █▄▄▄▄▄██  ▀██▄▄▄▄█    ██▄▄▄   ▀██▄▄▄▄█  ██    ██    ████
#   ▀▀▀▀ ▀▀  ▀▀    ▀▀   ▀▀▀▀▀▀     ▀▀▀▀▀      ▀▀▀▀     ▀▀▀▀▀   ▀▀    ▀▀     ▀▀
#
#
# --- DESCRIPTION --- #
# Copy unset command for selected env vars
# --- DEPENDENCIES --- #
# - env
# - fzf
# - awk
# - wc
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
declare -a vars

output=$(printenv | fzf | awk -F = '{print $1}')

if [[ $(echo "${output}" | wc -w) == 1 ]]; then
  clipcopy "unset ${output}" && log-success "Copied output to clipboard"
else
  mapfile -t vars <<<"${output}"
  clipcopy "unset ${vars[*]}" && log-success "Copied output to clipboard"
fi
