#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#               ██                         ▄▄▄▄         ██
#               ▀▀                         ▀▀██         ▀▀
#  ██▄  ▄██   ████      ▄████▄  ██      ██   ██       ████     ██▄████▄   ▄████▄   ▄▄█████▄
#   ██  ██      ██     ██▄▄▄▄██ ▀█  ██  █▀   ██         ██     ██▀   ██  ██▄▄▄▄██  ██▄▄▄▄ ▀
#   ▀█▄▄█▀      ██     ██▀▀▀▀▀▀  ██▄██▄██    ██         ██     ██    ██  ██▀▀▀▀▀▀   ▀▀▀▀██▄
#    ████    ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ▀██  ██▀    ██▄▄▄   ▄▄▄██▄▄▄  ██    ██  ▀██▄▄▄▄█  █▄▄▄▄▄██
#     ▀▀     ▀▀▀▀▀▀▀▀    ▀▀▀▀▀    ▀▀  ▀▀      ▀▀▀▀   ▀▀▀▀▀▀▀▀  ▀▀    ▀▀    ▀▀▀▀▀    ▀▀▀▀▀▀
#
#
# --- DESCRIPTION --- #
# View a specific line or range of lines from a text file.
#   viewlines filename 15     -> Views line 15
#   viewlines filename 10 20  -> Views lines 10 through 20
#   viewlines filename 10 -   -> Views lines 10 through end of file
# --- DEPENDENCIES --- #
# - awk
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

source "$(include "lib/cmdarg.sh")"
source "$(include "lib/helpers.sh")"
source "$(include "check-deps")"
checkDeps "$0"

# --- cmdarg setup --- #
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
if ((argc < 2 || argc > 3)); then
  cmdarg_usage
  exit 2
fi

file="${argv[0]}"
[[ -e "${file}" ]] || log-error "File ${file} doesn't exist"

start="${argv[1]}"
isPositive "${start}" || log-error "Start must be a positive number"

lines="$(awk 'END{print NR}' "${file}")"
((start > lines)) && log-error "File: ${file} has only ${lines} lines!"

if ((argc == 2)); then
  # Single line mode: NR is the current line number
  awk "NR == ${start} {print; exit}" "${file}"
elif ((argc == 3)); then
  end="${argv[2]}"

  # Read from start to the end of the file
  if [[ "${end}" == "-" ]]; then
    awk "NR >= ${start}" "${file}"
    exit 0
  fi

  isPositive "${end}" || log-error "End must be a positive number"
  ((start <= end)) || log-error "Start must be less than or equal to End"
  ((end > lines)) && log-error "File: ${file} has only ${lines} lines!"

  # Range mode: Prints between start and end, then exits
  awk "NR >= ${start} && NR <= ${end}; NR == ${end} {exit}" "${file}"
fi
