#!/usr/bin/env bash
#
# --- SCRIPT SIGNATURE --- #
#
#            ▄▄           ██               ▄▄
#            ██           ▀▀               ██
# ██      ██ ██▄████▄   ████      ▄█████▄  ██▄████▄             ▄█████▄  ██▄███▄   ██▄███▄
# ▀█  ██  █▀ ██▀   ██     ██     ██▀    ▀  ██▀   ██            ██▀    ▀  ██▀  ▀██  ██▀  ▀██
#  ██▄██▄██  ██    ██     ██     ██        ██    ██   █████    ██        ██    ██  ██    ██
#  ▀██  ██▀  ██    ██  ▄▄▄██▄▄▄  ▀██▄▄▄▄█  ██    ██            ▀██▄▄▄▄█  ███▄▄██▀  ███▄▄██▀
#   ▀▀  ▀▀   ▀▀    ▀▀  ▀▀▀▀▀▀▀▀    ▀▀▀▀▀   ▀▀    ▀▀              ▀▀▀▀▀   ██ ▀▀▀    ██ ▀▀▀
#                                                                        ██        ██
#
# --- DESCRIPTION --- #
# Detects the first available C++ compiler and prints its version
# --- DEPENDENCIES --- #
# - awk
# --- END SIGNATURE --- #

set -eo pipefail
trap 'exit 1' SIGUSR1

eval "$(include "lib/cmdarg.sh")"
eval "$(include "check-deps")"

checkDeps "$0"
cmdarg_info "header" "$(get-desc "$0")"
cmdarg_parse "$@"
# ---  Main script logic --- #
for compiler in g++ clang++ c++; do
  if command -v "${compiler}" &>/dev/null; then
    version="$("${compiler}" --version | head -n1)"
    break
  fi
done

echo "${version}" | awk '
{
  if ($1 == "g++") {
    printf "%s v%s", $1, $3
  } else if ($1 == "Free") {
    printf "g++ v%s", $4
  } else if ($1 == "clang") {
    printf "clang++ v%s", $3
  } else {
    printf "%s v%s", $1, $3
  }
}'
