#!/usr/bin/env bash

for compiler in clang++ g++ c++; do
  if command -v "${compiler}" &> /dev/null; then
    version="$("${compiler}" --version | head -n1)"
    break
  fi
done

echo "${version}" | awk '
{
  if ($1 == "g++") {
    printf "%s v%s", $1, $3
  } else if ($1 == "Free") {
    printf "g++ v%s", $4
  } else if ($1 == "clang") {
    printf "clang++ v%s", $3
  } else {
    printf "%s v%s", $1, $3
  }
}'
