#!/usr/bin/env bash

# Import Current Theme
RASI="$(dirname "$0")/music.rasi"
PATH="${PATH}:${HOME}/.local/bin/scripts"

# Theme Elements
status="$(spotifyctl current)"
if [[ "${status}" == "Offline" ]]; then
  prompt="${status}"
  mesg="Spotify is Offline"
else
  prompt="$(spotifyctl status --format '{artist}')"
  mesg="$(spotifyctl status --format '{artist} :: {title}')"
fi

# Options
layout=$(rg 'USE_ICON' "${RASI}" | cut -d'=' -f2)
if [[ "${layout}" == 'NO' ]]; then
  if [[ ${status} == "playing" ]]; then
    option_1=" Pause"
  else
    option_1="  Play"
  fi
  option_2="  Stop"
  option_3="  Previous"
  option_4="  Next"
else
  if [[ ${status} == "playing" ]]; then
    option_1="  "
  else
    option_1="  "
  fi
  option_2="  "
  option_3="  "
  option_4="  "
fi

# Rofi CMD
rofi_cmd() {
  rofi -dmenu \
    -p "${prompt}" \
    -mesg "${mesg}" \
    -markup-rows \
    -theme "${RASI}"
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "${option_1}\n${option_2}\n${option_3}\n${option_4}" | rofi_cmd
}

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    spotifyctl play-pause
  elif [[ "$1" == '--opt2' ]]; then
    spotifyctl stop
  elif [[ "$1" == '--opt3' ]]; then
    spotifyctl previous
  elif [[ "$1" == '--opt4' ]]; then
    spotifyctl next
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
"${option_1}")
  run_cmd --opt1
  ;;
"${option_2}")
  run_cmd --opt2
  ;;
"${option_3}")
  run_cmd --opt3
  ;;
"${option_4}")
  run_cmd --opt4
  ;;
*) exit 0 ;;
esac
