#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
RASI="$(dirname $0)/askpass.rasi"

# rofi text dialog to get password
rofi -dmenu \
  -password \
  -i \
  -p "Root" \
  -theme "${RASI}"
