#!/usr/bin/env bash
#
# Script name: dm-man
# Description: Search for a tldr page or get a random one.
# Dependencies: dmenu, fzf, rofi, kitty, tldr
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Simon Ingelsson

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null

source_dmscripts_configs

if configs_are_different; then
  echo "$(date): configs are different" >>"${DM_CONFIG_DIFF_LOGFILE}"
  sleep 1
fi

run_tldr() {
  eval "${DMTERM} tldr \"$1\""
}
export -f run_tldr

main() {

  tldr --list-all |
    ${MENU} 'Search for: ' |
    xargs -I {} tldr {}

}

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
